project_id = "ozuatdcakezjtevztjlr"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:8080/**",
  "http://127.0.0.1:8080/**",
  "https://4df4bbcc-252d-4ed5-879c-06ba36a68902.lovableproject.com/**",
  "https://id-preview--4df4bbcc-252d-4ed5-879c-06ba36a68902.lovable.app/**",
  "https://overdraft-drafting-site.lovable.app/**",
  "https://preview--overdraft-drafting-site.lovable.app/**",
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
