// Provenance:
// - Quotes Spreadsheet - Improved.xlsx
// - Batch QB00002
// - Files 1093-05589-02.STEP and 1093-05589-02.pdf

export const QUOTED_SAMPLE_SOURCE = Object.freeze({
  workbookName: "Quotes Spreadsheet - Improved.xlsx",
  batch: "QB00002",
  partNumber: "1093-05589",
  revision: "2",
})

export const QUOTED_SAMPLE_ASSETS = Object.freeze({
  cad: Object.freeze({
    fileName: "1093-05589-02.STEP",
    normalizedName: "1093-05589-02.STEP",
    storagePath: "fixtures/1093-05589-02.STEP",
  }),
  drawing: Object.freeze({
    fileName: "1093-05589-02.pdf",
    normalizedName: "1093-05589-02.pdf",
    storagePath: "fixtures/1093-05589-02.pdf",
  }),
})

export const QUOTED_SAMPLE_RFQ = Object.freeze({
  client: "4D Technology",
  projectSystem: "Carbon Fiber End Attachment",
  rfqReceivedDate: "2026-02-28",
  quoteDueDate: "2026-03-18",
  quotedDate: "2026-03-03",
  totalQuotedUsd: 423.7,
  notes: "5 suppliers, 16 options. Best: Xometry Intl Economy $423.70",
})

export const QUOTED_SAMPLE_PART = Object.freeze({
  projectName: "Carbon Fiber End Attachment",
  projectDescription: "Workbook-backed quoted sample for debug and review surfaces.",
  jobTitle: "1093-05589 rev 2",
  jobDescription: "BONDED, CARBON FIBER END ATTACHMENT",
  partNumber: "1093-05589",
  revision: "2",
  description: "BONDED, CARBON FIBER END ATTACHMENT",
  quantity: 10,
  requestedQuoteQuantities: Object.freeze([10]),
  requestedByDate: "2026-03-18",
  process: "CNC Machining",
  material: "6061-T6x (Best Available)",
  finish: "Black Anodize",
  tightestToleranceInch: 0.005,
  tightestToleranceLabel: '+/-.005"',
  toleranceSource: "Title block (3-place decimal)",
  threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
  threadMatchNotes:
    "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
  selectedLaneId: "xometry-international-economy",
})

export const QUOTED_SAMPLE_LANES = Object.freeze([
  Object.freeze({
    id: "xometry-international-economy",
    vendor: "xometry",
    supplier: "Xometry",
    sourcing: "International",
    tier: "Economy",
    laneLabel: "Economy",
    requestedQuantity: 10,
    unitPriceUsd: 42.37,
    totalPriceUsd: 423.7,
    leadTimeBusinessDays: 14,
    shipReceiveBy: "Mar 23",
    dueDate: "Mar 18",
    quoteRef: "Q50-9761-1947",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061-T6x (Best Available)",
    finish: "Black Anodize",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes:
      "Must order by 11:59PM ET to ship by Mar 23. 125uin/3.2um Ra. Formal inspection w/ dimensional report.",
  }),
  Object.freeze({
    id: "xometry-usa-economy",
    vendor: "xometry",
    supplier: "Xometry",
    sourcing: "USA",
    tier: "Economy",
    laneLabel: "Economy",
    requestedQuantity: 10,
    unitPriceUsd: 112.12,
    totalPriceUsd: 1121.2,
    leadTimeBusinessDays: 19,
    shipReceiveBy: "Mar 30",
    dueDate: "Mar 18",
    quoteRef: "Q50-9761-1947",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061-T6x (Best Available)",
    finish: "Black Anodize",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: null,
  }),
  Object.freeze({
    id: "xometry-usa-standard",
    vendor: "xometry",
    supplier: "Xometry",
    sourcing: "USA",
    tier: "Standard",
    laneLabel: "Standard",
    requestedQuantity: 10,
    unitPriceUsd: 140.54,
    totalPriceUsd: 1405.4,
    leadTimeBusinessDays: 11,
    shipReceiveBy: "Mar 18",
    dueDate: "Mar 18",
    quoteRef: "Q50-9761-1947",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061-T6x (Best Available)",
    finish: "Black Anodize",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: null,
  }),
  Object.freeze({
    id: "xometry-usa-expedite",
    vendor: "xometry",
    supplier: "Xometry",
    sourcing: "USA",
    tier: "Expedite",
    laneLabel: "Expedite",
    requestedQuantity: 10,
    unitPriceUsd: 256.3,
    totalPriceUsd: 2563,
    leadTimeBusinessDays: 7,
    shipReceiveBy: "Mar 12",
    dueDate: "Mar 18",
    quoteRef: "Q50-9761-1947",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061-T6x (Best Available)",
    finish: "Black Anodize",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: null,
  }),
  Object.freeze({
    id: "protolabs-expedite",
    vendor: "protolabs",
    supplier: "Protolabs",
    sourcing: null,
    tier: "Expedite",
    laneLabel: "Expedite",
    requestedQuantity: 10,
    unitPriceUsd: 365.54,
    totalPriceUsd: 3655.4,
    leadTimeBusinessDays: null,
    shipReceiveBy: "Mar 12",
    dueDate: "Mar 18",
    quoteRef: "Quote 8779-568",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "Aluminum 6061-T651/T6",
    finish: "Anodize Type II, Black (MIL-A-8625F)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "$2,523.40 parts + $180.00 anodizing. Sharp internal corners w/ min tool radius.",
  }),
  Object.freeze({
    id: "protolabs-standard",
    vendor: "protolabs",
    supplier: "Protolabs",
    sourcing: null,
    tier: "Standard",
    laneLabel: "Standard",
    requestedQuantity: 10,
    unitPriceUsd: 270.34,
    totalPriceUsd: 2703.4,
    leadTimeBusinessDays: null,
    shipReceiveBy: "Mar 13",
    dueDate: "Mar 18",
    quoteRef: "Quote 8779-568",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "Aluminum 6061-T651/T6",
    finish: "Anodize Type II, Black (MIL-A-8625F)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "Machining tolerance +/-0.005 in (0.13mm).",
  }),
  Object.freeze({
    id: "protolabs-economy",
    vendor: "protolabs",
    supplier: "Protolabs",
    sourcing: null,
    tier: "Economy",
    laneLabel: "Economy",
    requestedQuantity: 10,
    unitPriceUsd: 222.74,
    totalPriceUsd: 2227.4,
    leadTimeBusinessDays: null,
    shipReceiveBy: "Mar 19",
    dueDate: "Mar 18",
    quoteRef: "Quote 8779-568",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "Aluminum 6061-T651/T6",
    finish: "Anodize Type II, Black (MIL-A-8625F)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: null,
  }),
  Object.freeze({
    id: "sendcutsend-standard",
    vendor: "sendcutsend",
    supplier: "SendCutSend",
    sourcing: null,
    tier: "Standard",
    laneLabel: "Standard",
    requestedQuantity: 10,
    unitPriceUsd: 164.89,
    totalPriceUsd: 1648.9,
    leadTimeBusinessDays: 10,
    shipReceiveBy: "Mar 18-19",
    dueDate: "Mar 18",
    quoteRef: null,
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 T6 Aluminum",
    finish: "Black Anodizing",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "Free shipping. Tax est. $106.51 not included.",
  }),
  Object.freeze({
    id: "sendcutsend-overnight",
    vendor: "sendcutsend",
    supplier: "SendCutSend",
    sourcing: null,
    tier: "Overnight",
    laneLabel: "Overnight",
    requestedQuantity: 10,
    unitPriceUsd: 168.79,
    totalPriceUsd: 1687.9,
    leadTimeBusinessDays: null,
    shipReceiveBy: "Mar 17",
    dueDate: "Mar 18",
    quoteRef: null,
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 T6 Aluminum",
    finish: "Black Anodizing",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "+$39 overnight shipping.",
  }),
  Object.freeze({
    id: "partsbadger-standard",
    vendor: "partsbadger",
    supplier: "PartsBadger",
    sourcing: null,
    tier: "Standard",
    laneLabel: "Standard",
    requestedQuantity: 10,
    unitPriceUsd: 122.42,
    totalPriceUsd: 1224.2,
    leadTimeBusinessDays: 16,
    shipReceiveBy: "Mar 25",
    dueDate: "Mar 18",
    quoteRef: null,
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061",
    finish: "Anodize Black",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "Surface finish: Deburr. Tax est. $106.51. Shipping TBD at checkout.",
  }),
  Object.freeze({
    id: "fictiv-north-america-fastest",
    vendor: "fictiv",
    supplier: "Fictiv",
    sourcing: "North America",
    tier: "Fastest",
    laneLabel: "Fastest",
    requestedQuantity: 10,
    unitPriceUsd: 240.03,
    totalPriceUsd: 2400.3,
    leadTimeBusinessDays: 6,
    shipReceiveBy: "Mar 11",
    dueDate: "Mar 18",
    quoteRef: "wilson_022826",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 Aluminum (T6/T651/T6511)",
    finish: "Anodize per MIL-PRF-8625 Type II (Black, Sealed)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "Acct mgr: saran.krishna@fictiv.com / 786-701-1616.",
  }),
  Object.freeze({
    id: "fictiv-north-america-standard",
    vendor: "fictiv",
    supplier: "Fictiv",
    sourcing: "North America",
    tier: "Standard",
    laneLabel: "Standard",
    requestedQuantity: 10,
    unitPriceUsd: 214.37,
    totalPriceUsd: 2143.7,
    leadTimeBusinessDays: 8,
    shipReceiveBy: "Mar 13",
    dueDate: "Mar 18",
    quoteRef: "wilson_022826",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 Aluminum (T6/T651/T6511)",
    finish: "Anodize per MIL-PRF-8625 Type II (Black, Sealed)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: null,
  }),
  Object.freeze({
    id: "fictiv-north-america-cost-effective",
    vendor: "fictiv",
    supplier: "Fictiv",
    sourcing: "North America",
    tier: "Cost-effective",
    laneLabel: "Cost-effective",
    requestedQuantity: 10,
    unitPriceUsd: 180.29,
    totalPriceUsd: 1802.9,
    leadTimeBusinessDays: 14,
    shipReceiveBy: "Mar 23",
    dueDate: "Mar 18",
    quoteRef: "wilson_022826",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 Aluminum (T6/T651/T6511)",
    finish: "Anodize per MIL-PRF-8625 Type II (Black, Sealed)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: null,
  }),
  Object.freeze({
    id: "fictiv-overseas-fastest",
    vendor: "fictiv",
    supplier: "Fictiv",
    sourcing: "Overseas",
    tier: "Fastest",
    laneLabel: "Fastest",
    requestedQuantity: 10,
    unitPriceUsd: 121.63,
    totalPriceUsd: 1216.3,
    leadTimeBusinessDays: 7,
    shipReceiveBy: "Mar 12",
    dueDate: "Mar 18",
    quoteRef: "wilson_022826",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 Aluminum (T6/T651/T6511)",
    finish: "Anodize per MIL-PRF-8625 Type II (Black, Sealed)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "Duties & tariffs not included.",
  }),
  Object.freeze({
    id: "fictiv-overseas-standard",
    vendor: "fictiv",
    supplier: "Fictiv",
    sourcing: "Overseas",
    tier: "Standard",
    laneLabel: "Standard",
    requestedQuantity: 10,
    unitPriceUsd: 79.12,
    totalPriceUsd: 791.2,
    leadTimeBusinessDays: 10,
    shipReceiveBy: "Mar 17",
    dueDate: "Mar 18",
    quoteRef: "wilson_022826",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 Aluminum (T6/T651/T6511)",
    finish: "Anodize per MIL-PRF-8625 Type II (Black, Sealed)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "Duties & tariffs not included.",
  }),
  Object.freeze({
    id: "fictiv-overseas-cost-effective",
    vendor: "fictiv",
    supplier: "Fictiv",
    sourcing: "Overseas",
    tier: "Cost-effective",
    laneLabel: "Cost-effective",
    requestedQuantity: 10,
    unitPriceUsd: 68.66,
    totalPriceUsd: 686.6,
    leadTimeBusinessDays: 14,
    shipReceiveBy: "Mar 23",
    dueDate: "Mar 18",
    quoteRef: "wilson_022826",
    quoteDate: "2026-03-03",
    process: "CNC Machining",
    material: "6061 Aluminum (T6/T651/T6511)",
    finish: "Anodize per MIL-PRF-8625 Type II (Black, Sealed)",
    tightestTolerance: '+/-.005"',
    toleranceSource: "Title block (3-place decimal)",
    threadCallouts: ".317 THRU ALL (clearance hole, unthreaded)",
    threadMatchNotes:
      "No threaded features - .317 clearance hole likely slip-fit over mating stud body",
    notes: "Duties & tariffs not included.",
  }),
])

export const QUOTED_SAMPLE_SUPPLIER_COUNT = new Set(
  QUOTED_SAMPLE_LANES.map((lane) => lane.vendor),
).size

export const QUOTED_SAMPLE_LANE_COUNT = QUOTED_SAMPLE_LANES.length

export function getQuotedSampleSelectedLane() {
  return (
    QUOTED_SAMPLE_LANES.find((lane) => lane.id === QUOTED_SAMPLE_PART.selectedLaneId) ?? QUOTED_SAMPLE_LANES[0]
  )
}
