-- Generated by scripts/generate-free-quote-fixtures.mjs; do not edit.
-- Source: supabase/tests/free_quote_job_meter.sql SHA-256 2c3478d618a5a3603e4a15e1ea94e7cf96c4201ec0b721c0a369ed07be1222f0
\set ON_ERROR_STOP on
set search_path=public,extensions;
set statement_timeout='45s';
set lock_timeout='5s';
-- Run only after BOTH meter and confirmed-admission migrations are applied.
-- This file rolls back its synthetic fixtures. It has not run without a DB.
begin;
select no_plan();
\set meter_fixture_limit 20
-- BEGIN exact include supabase/tests/fixtures/free_quote_meter_setup.inc SHA-256 3f35533f003968c89d74198812be3bbd10ad7c636820fd0143f0bf6c87f937d8
-- Synthetic fixture only; execute in an isolated disposable database.
create schema free_meter_fixture;
create function free_meter_fixture.set_identity(p_user_id uuid)
returns void
language plpgsql
set search_path = pg_catalog
as $$
begin
  perform pg_catalog.set_config(
    'request.jwt.claims',
    pg_catalog.jsonb_build_object(
      'sub', p_user_id,
      'role', 'authenticated', -- NOSONAR: repeated authenticated JWT fixture claim
      'aal', 'aal1'
    )::text,
    true
  );
  perform pg_catalog.set_config('request.jwt.claim.sub', p_user_id::text, true);
  perform pg_catalog.set_config('request.jwt.claim.role', 'authenticated', true);
end;
$$;

create table free_meter_fixture.context (
  user_id uuid not null,
  organization_id uuid not null,
  job_id uuid not null,
  part_id uuid not null,
  approval_reference uuid not null,
  scope_fingerprint text,
  rollback_scope_fingerprint text,
  quote_run_id uuid
);

insert into free_meter_fixture.context values (
  '00000000-0000-4000-8000-000000008811',
  '00000000-0000-4000-8000-000000008812',
  '00000000-0000-4000-8000-000000008813',
  '00000000-0000-4000-8000-000000008814',
  '00000000-0000-4000-8000-000000008815',
  null,
  null,
  null
);

grant select, update on free_meter_fixture.context to authenticated;

insert into auth.users (id, aud, role, email, email_confirmed_at)
values (
  (select user_id from free_meter_fixture.context),
  'authenticated',
  'authenticated',
  'free-meter-member@example.test',
  timezone('utc', now())
);

insert into public.organizations (id, name, slug)
values (
  (select organization_id from free_meter_fixture.context),
  'Free meter Dispatch',
  'free-meter-dispatch'
);

insert into public.organization_memberships (organization_id, user_id, role)
select organization_id, user_id, 'client'
from free_meter_fixture.context;

-- This dispatch fixture starts after an administrator confirmed its destination.
update public.organizations set shipping_same_as_billing=false, shipping_street='123 Fixture Ave',
  shipping_city='Tucson', shipping_state='AZ', shipping_zip='85701', shipping_country='US'
where id=(select organization_id from free_meter_fixture.context);
insert into private.sourcing_destination_history (organization_id, state, address)
select organization_id, 'confirmed', private.effective_sourcing_address(organization_id) from free_meter_fixture.context;

update private.commercial_rollout_controls
set enabled = true,
    revision = revision + 1,
    change_reason = 'Free-meter local pgTAP fixture'
where capability = 'automatic_quote_collection'; -- NOSONAR: canonical rollout capability fixture is exercised across preflight states

insert into public.jobs (
  id, organization_id, created_by, title, status,
  requested_service_kinds, primary_service_kind
)
select job_id, organization_id, user_id, 'Free-meter validation part',
  'ready_to_quote', array['manufacturing_quote'], 'manufacturing_quote' -- NOSONAR: deterministic quote-envelope fixture
from free_meter_fixture.context;

insert into public.jobs (
  id, organization_id, created_by, title, status,
  requested_service_kinds, primary_service_kind
)
select '00000000-0000-4000-8000-000000008821', organization_id, user_id, -- NOSONAR: deterministic fixture identifier
  'Free-meter rollback part', 'ready_to_quote',
  array['manufacturing_quote'], 'manufacturing_quote'
from free_meter_fixture.context;

insert into public.organization_file_blobs (
  id, organization_id, content_sha256, trusted_content_sha256,
  storage_bucket, storage_path, size_bytes, mime_type
)
select
  '00000000-0000-4000-8000-000000008816', organization_id,
  repeat('a', 64), repeat('a', 64), 'job-files', -- NOSONAR: deterministic trusted-file hash and bucket fixture
  organization_id::text || '/sha256/' || repeat('a', 64) || '/part.step', -- NOSONAR: deterministic trusted storage path
  100, 'application/step' -- NOSONAR: canonical STEP MIME fixture
from free_meter_fixture.context;

insert into public.job_files (
  id, job_id, organization_id, uploaded_by, blob_id, content_sha256,
  trusted_content_sha256, storage_bucket, storage_path, original_name,
  normalized_name, file_kind, mime_type, size_bytes
)
select
  '00000000-0000-4000-8000-000000008817', job_id, organization_id, -- NOSONAR: deterministic fixture identifier
  user_id, '00000000-0000-4000-8000-000000008816', repeat('a', 64),
  repeat('a', 64), 'job-files',
  organization_id::text || '/sha256/' || repeat('a', 64) || '/part.step',
  'part.step', 'part', 'cad', 'application/step', 100
from free_meter_fixture.context;

insert into public.parts (
  id, job_id, organization_id, name, normalized_key, cad_file_id, quantity
)
select part_id, job_id, organization_id, 'Validation part', 'validation-part',
  '00000000-0000-4000-8000-000000008817', 1
from free_meter_fixture.context;

insert into public.approved_part_requirements (
  part_id, organization_id, approved_by, material, finish,
  tightest_tolerance_inch, quantity, quote_quantities,
  applicable_vendors, spec_snapshot
)
select part_id, organization_id, user_id, '6061-T6 Aluminum', 'As machined', -- NOSONAR: canonical controlled-beta material and finish fixture
  0.0050, 1, array[1], array['xometry']::public.vendor_name[], -- NOSONAR: canonical tolerance, quantity, provider, and transport-scale fixture
  '{"process":"CNC milling","tightestToleranceInch":0.0050}'::jsonb -- NOSONAR: canonical process and transport-scale fixture
from free_meter_fixture.context;


-- Synthetic fixtures only: no production allowance or enrollment selected.
insert into private.founding_beta_enrollment_events(organization_id,actor_user_id,action,reason,policy_revision,terms_path,privacy_path,idempotency_key)
select organization_id,user_id,'grant','free access fixture','founding-beta-2026-08-15','/legal/beta-terms','/legal/privacy','free-access-grant' from free_meter_fixture.context;
insert into private.founding_beta_notice_acceptances(organization_id,user_id,policy_revision,terms_path,privacy_path)
select organization_id,user_id,'founding-beta-2026-08-15','/legal/beta-terms','/legal/privacy' from free_meter_fixture.context;
insert into public.org_vendor_configs(organization_id,vendor,enabled_for_client_quote_requests)
select organization_id,'xometry',true from free_meter_fixture.context;


-- Keep the pre-existing request/spend guards enabled; explicit larger fixture
-- settings let this one SQL test exercise independent cases without choosing a
-- production allowance or removing any admission check.
insert into public.quote_request_guardrails(organization_id,user_max_requests_per_window,org_pending_cost_ceiling_usd)
select organization_id,100,100000 from free_meter_fixture.context;
insert into private.free_quote_policies(revision,enabled,subject_kind,completed_limit,window_start,window_end)
values ('synthetic-meter-only',true,'organization',:meter_fixture_limit,clock_timestamp()-interval '1 minute',clock_timestamp()+interval '1 hour');

create table free_meter_fixture.spend_before(id uuid primary key, original_row jsonb not null);

create function free_meter_fixture.new_request()
returns uuid language plpgsql as $$
declare
 v_user uuid; v_org uuid; v_job uuid:=gen_random_uuid(); v_part uuid:=gen_random_uuid();
 v_file uuid:=gen_random_uuid(); v_scope jsonb; v_response jsonb;
begin
 select user_id,organization_id into v_user,v_org from free_meter_fixture.context;
 perform free_meter_fixture.set_identity(v_user);
 insert into public.jobs(id,organization_id,created_by,title,status,requested_service_kinds,primary_service_kind)
 values(v_job,v_org,v_user,'Synthetic meter case','ready_to_quote',array['manufacturing_quote'],'manufacturing_quote');
 insert into public.job_files(id,job_id,organization_id,uploaded_by,blob_id,content_sha256,trusted_content_sha256,
 storage_bucket,storage_path,original_name,normalized_name,file_kind,mime_type,size_bytes)
 select v_file,v_job,organization_id,uploaded_by,blob_id,content_sha256,trusted_content_sha256,
 storage_bucket,storage_path,'case.step','case','cad',mime_type,size_bytes from public.job_files
 where id='00000000-0000-4000-8000-000000008817';
 insert into public.parts(id,job_id,organization_id,name,normalized_key,cad_file_id,quantity)
 values(v_part,v_job,v_org,'Meter part','meter-part',v_file,1);
 insert into public.approved_part_requirements(part_id,organization_id,approved_by,material,finish,
 tightest_tolerance_inch,quantity,quote_quantities,applicable_vendors,spec_snapshot)
 values(v_part,v_org,v_user,'6061-T6 Aluminum','As machined',0.005,1,array[1],array['xometry']::public.vendor_name[],
 '{"process":"CNC milling","tightestToleranceInch":0.0050}'::jsonb);
 v_scope:=public.api_get_xometry_beta_dispatch_scope(v_job,'inch');
 v_response:=public.api_request_xometry_beta_dispatch(v_job,'inch',v_scope->>'scopeFingerprint',
 'founding-beta-2026-08-15',gen_random_uuid(),true,true,true);
 if (v_response->>'accepted')::boolean is not true then raise exception 'fixture admission failed: %',v_response->>'reasonCode'; end if;
 -- Synthetic accounting observations, not charges: prove quota outcomes never
 -- discard attempted known or unresolved spend for this exact run.
 with inserted as (
   insert into public.spend_ledger(organization_id,category,amount_usd,settled,settled_at,job_id,quote_run_id,metadata)
   values (v_org,'vendor_automation',0.025,true,clock_timestamp(),v_job,(v_response->>'quoteRunId')::uuid,'{"fixture":"free-meter-known"}'::jsonb),
          (v_org,'llm_extraction',0.5,false,null,v_job,(v_response->>'quoteRunId')::uuid,'{"fixture":"free-meter-pending"}'::jsonb)
   returning *
 ) insert into free_meter_fixture.spend_before select id,to_jsonb(inserted) from inserted;
 return (v_response->>'quoteRequestId')::uuid;
end;
$$;
create function free_meter_fixture.result_id(p_request uuid)
returns uuid language sql as $$ select vendor_quote_result_id from private.xometry_beta_dispatch_permits where quote_request_id=p_request $$;
create function free_meter_fixture.offers(p_request uuid,p_price numeric default 12,p_valid_until timestamptz default clock_timestamp()+interval '1 day',p_provenance text default 'trusted_adapter')
returns jsonb language sql as $$
 select jsonb_build_array(jsonb_build_object('vendor_quote_result_id',permit.vendor_quote_result_id,
 'organization_id',permit.organization_id,'offer_key','fixture-offer','supplier','Xometry','lane_label','Fixture',
 'geographic_origin','unknown','quoted_at',clock_timestamp()-interval '1 minute','valid_until',p_valid_until,
 'validity_source','vendor_date','provenance_status',p_provenance,'unit_price_usd',p_price,'total_price_usd',p_price,
 'sort_rank',0,'raw_payload','{}'::jsonb)) from private.xometry_beta_dispatch_permits permit where quote_request_id=p_request
$$;
create function free_meter_fixture.result_payload(p_status text default 'instant_quote_received')
returns jsonb language sql as $$ select jsonb_build_object('status',p_status,'unit_price_usd',12,'total_price_usd',12,
 'notes','[]'::jsonb,'dfm_issues','[]'::jsonb,'raw_payload','{}'::jsonb) $$;

-- END exact include supabase/tests/fixtures/free_quote_meter_setup.inc

select ok(not has_table_privilege('authenticated','private.quote_access_admissions','INSERT'),'clients cannot forge receipts');
select ok(not has_table_privilege('service_role','private.quote_access_admissions','UPDATE'),'service cannot directly rewrite receipts');
select ok(not has_function_privilege('authenticated','private.finalize_free_quote_job(uuid)','EXECUTE'),'clients cannot self-certify completion');
select ok(not has_function_privilege('service_role','private.record_quote_access_admission(uuid,uuid,text,uuid)','EXECUTE'),'service cannot bypass admission wrapper');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='private.quote_access_admissions'::regclass),'receipt RLS forced');
set local role authenticated;
select throws_ok($$select private.finalize_free_quote_job('00000000-0000-4000-8000-000000000001'::uuid)$$,'42501',null,'actual authenticated execution cannot self-certify');
select throws_ok($$select * from private.quote_access_admissions$$,'42501',null,'actual authenticated execution cannot enumerate private receipts');
reset role;
set local role service_role;
select throws_ok($$update private.quote_access_admissions set state='consumed'$$,'42501',null,'actual service transport cannot mutate private receipts');
reset role;

select throws_ok($$insert into private.free_quote_policies(revision,enabled,subject_kind,completed_limit,window_start,window_end)
values('synthetic-reset',true,'user',200,clock_timestamp(),clock_timestamp()+interval '1 hour')$$,'23P01',null,'overlapping revision cannot reset window/subject/cap');
update private.free_quote_policies set enabled=false where revision='synthetic-meter-only';
select throws_ok($$insert into private.free_quote_policies(revision,enabled,subject_kind,completed_limit,window_start,window_end)
values('synthetic-reset-disabled',true,'organization',200,clock_timestamp(),clock_timestamp()+interval '1 hour')$$,'23P01',null,'disabled history still prevents reset');
select throws_ok($$update private.free_quote_policies set completed_limit=21 where revision='synthetic-meter-only'$$,'P0001','free_quote_policy_immutable','policy cap immutable');
update private.free_quote_policies set enabled=true where revision='synthetic-meter-only';

create temporary table cases(name text primary key,request_id uuid not null);
insert into cases values('success',free_meter_fixture.new_request());
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='success')),'reserved','new request holds one slot');
-- Force constraint timing early: successful result must not release before offers.
set constraints all immediate;
select lives_ok(format('select public.reconcile_vendor_quote_offers(%L::uuid,%L::jsonb,%L::jsonb)',
 free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id)),
 'canonical valid offer succeeds with constraints immediate') from cases where name='success';
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='success')),'consumed','one usable quote consumes once');
select is(private.finalize_free_quote_job((select request_id from cases where name='success'))->>'changed','false','reconcile receipt is idempotent');
select lives_ok(format('select public.reconcile_vendor_quote_offers(%L::uuid,%L::jsonb,%L::jsonb)',
 free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id)),
 'successful canonical replay does not double count') from cases where name='success';
select is((select count(*)::integer from private.quote_access_admissions where state='consumed'),1,'one consumed regardless of replay');
select is(public.api_cancel_quote_request((select request_id from cases where name='success'))->>'reasonCode','already_received','completed result wins cancellation');
select throws_ok(format('update public.vendor_quote_results set status=''running'' where id=%L::uuid',
 free_meter_fixture.result_id((select request_id from cases where name='success'))),'P0001','free_quote_terminal_fenced','consumed request cannot reopen');
update public.vendor_quote_offers set invalidated_at=clock_timestamp(),invalidated_by=(select user_id from free_meter_fixture.context),invalidation_reason='Synthetic invalidation'
where vendor_quote_result_id=free_meter_fixture.result_id((select request_id from cases where name='success'));
select is(private.finalize_free_quote_job((select request_id from cases where name='success'))->>'state','consumed','historical receipt survives later invalidation');
select ok((select qualifying_evidence->>'scopeFingerprint'=scope_fingerprint from private.quote_access_admissions where state='consumed'),'completion pins scope evidence');
select throws_ok($$insert into private.quote_access_admissions(organization_id,actor_user_id,job_id,quote_request_id,quote_run_id,permit_id,
approval_reference,scope_version,scope_fingerprint,notice_revision,admission_source,bucket_id,policy_revision,state,terminal_at,outcome_reason,qualifying_offer_id,qualifying_evidence)
select organization_id,actor_user_id,job_id,gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),scope_version,scope_fingerprint,notice_revision,
admission_source,bucket_id,policy_revision,'consumed',clock_timestamp(),'usable_quote',gen_random_uuid(),null
from private.quote_access_admissions where state='consumed' limit 1$$,'23514',null,'consumed receipt cannot lack evidence');
select throws_ok($$insert into private.quote_access_admissions(organization_id,actor_user_id,job_id,quote_request_id,quote_run_id,permit_id,
approval_reference,scope_version,scope_fingerprint,notice_revision,admission_source,bucket_id,policy_revision,state,terminal_at,outcome_reason,qualifying_offer_id,qualifying_evidence)
select organization_id,actor_user_id,job_id,gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),scope_version,scope_fingerprint,notice_revision,
admission_source,bucket_id,policy_revision,'consumed',clock_timestamp(),null,gen_random_uuid(),'{}'::jsonb
from private.quote_access_admissions where state='consumed' limit 1$$,'23514',null,'consumed receipt rejects NULL outcome reason');

select throws_ok($$insert into private.quote_access_admissions(organization_id,actor_user_id,job_id,quote_request_id,quote_run_id,permit_id,
approval_reference,scope_version,scope_fingerprint,notice_revision,admission_source,bucket_id,policy_revision,state,terminal_at,outcome_reason,qualifying_offer_id,qualifying_evidence)
select organization_id,actor_user_id,job_id,gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),scope_version,scope_fingerprint,notice_revision,
admission_source,bucket_id,policy_revision,'released',clock_timestamp(),null,null,null
from private.quote_access_admissions where state='consumed' limit 1$$,'23514',null,'released receipt rejects NULL outcome reason');



insert into cases values('zero',free_meter_fixture.new_request());
select public.reconcile_vendor_quote_offers(free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id,0)) from cases where name='zero';
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='zero')),'consumed','known finite zero quote is usable');
insert into cases values('no-offer',free_meter_fixture.new_request());
select public.reconcile_vendor_quote_offers(free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),'[]'::jsonb) from cases where name='no-offer';
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='no-offer')),'released','canonical successful status alone does not consume');
select throws_ok(format('select public.reconcile_vendor_quote_offers(%L::uuid,%L::jsonb,%L::jsonb)',
 free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id)),
 'P0001','free_quote_terminal_fenced','late offer cannot resurrect released lifecycle') from cases where name='no-offer';

insert into cases values('nan',free_meter_fixture.new_request()),('expired',free_meter_fixture.new_request()),('unverified',free_meter_fixture.new_request());
select public.reconcile_vendor_quote_offers(free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id,'NaN'::numeric)) from cases where name='nan';
select public.reconcile_vendor_quote_offers(free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id,12,clock_timestamp()-interval '1 second')) from cases where name='expired';
select public.reconcile_vendor_quote_offers(free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id,12,clock_timestamp()+interval '1 day','unverified')) from cases where name='unverified';
select is((select count(*)::integer from private.quote_access_admissions where quote_request_id in(select request_id from cases where name in('nan','expired','unverified')) and state='released'),3,'NaN expired and unverified offers do not consume');

insert into cases values('retry',free_meter_fixture.new_request());
update public.vendor_quote_results set status='running' where id=free_meter_fixture.result_id((select request_id from cases where name='retry'));
update public.vendor_quote_results set status='queued' where id=free_meter_fixture.result_id((select request_id from cases where name='retry'));
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='retry')),'reserved','queued provider retry retains hold');
update public.work_queue set status='running' where quote_run_id=(select quote_run_id from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='retry'));
-- Exercise normal deferred timing explicitly; the earlier success case forced
-- all constraints immediate to prove it cannot see an incomplete offer set.
set constraints public.settle_terminal_free_quote_result deferred;
update public.vendor_quote_results set status='failed' where id=free_meter_fixture.result_id((select request_id from cases where name='retry'));
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='retry')),'reserved','failure is still held before deferred event fires');
set constraints public.settle_terminal_free_quote_result immediate;
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='retry')),'released','terminal result releases while task still running cleanup');
select is((select status::text from public.work_queue where quote_run_id=(select quote_run_id from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='retry')) and task_type='run_vendor_quote'),'running','fixture proves distinct cleanup state');

insert into cases values('obsolete-failure',free_meter_fixture.new_request());
set constraints public.settle_terminal_free_quote_result deferred;
update public.vendor_quote_results set status='failed' where id=free_meter_fixture.result_id((select request_id from cases where name='obsolete-failure'));
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='obsolete-failure')),'reserved','second failure remains reserved while deferred');
update public.vendor_quote_results set status='queued' where id=free_meter_fixture.result_id((select request_id from cases where name='obsolete-failure'));
set constraints public.settle_terminal_free_quote_result immediate;
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='obsolete-failure')),'reserved','obsolete failed event cannot release a currently queued retry');
set constraints public.settle_terminal_free_quote_result deferred;


insert into cases values('cancel',free_meter_fixture.new_request());
select is(public.api_cancel_quote_request((select request_id from cases where name='cancel'))->>'canceled','true','customer cancel wins before usable result');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='cancel')),'released','cancel releases hold');
select is(private.release_cancelled_free_quote_job((select request_id from cases where name='cancel'))->>'changed','false','cancel release idempotent');
select throws_ok(format('update public.vendor_quote_results set status=''instant_quote_received'' where id=%L::uuid',
 free_meter_fixture.result_id((select request_id from cases where name='cancel'))),'P0001','free_quote_terminal_fenced','late result cannot overwrite canceled request');
select is((select status::text from public.quote_requests where id=(select request_id from cases where name='cancel')),'canceled','request cancellation remains authoritative');

-- Corrupted cancellation binding is indeterminate, never a quota release.
insert into cases values('cancel-identity',free_meter_fixture.new_request());
update public.quote_requests set status='canceled',job_id=(select job_id from free_meter_fixture.context)
 where id=(select request_id from cases where name='cancel-identity');
select is(private.release_cancelled_free_quote_job((select request_id from cases where name='cancel-identity'))->>'reasonCode',
 'identity_indeterminate','canceled request with mismatched job retains hold');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='cancel-identity')),
 'reserved','mismatched cancellation cannot release receipt');
insert into cases values('cancel-run-identity',free_meter_fixture.new_request());
update public.quote_requests set status='canceled' where id=(select request_id from cases where name='cancel-run-identity');
update public.quote_runs set quote_request_id=null where id=(select quote_run_id from private.quote_access_admissions
 where quote_request_id=(select request_id from cases where name='cancel-run-identity'));
select is(private.release_cancelled_free_quote_job((select request_id from cases where name='cancel-run-identity'))->>'reasonCode',
 'identity_indeterminate','canceled request with unbound pinned run retains hold');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='cancel-run-identity')),
 'reserved','pinned run mismatch cannot release receipt');
insert into cases values('cancel-disabled-policy',free_meter_fixture.new_request());
update private.free_quote_policies set enabled=false where revision='synthetic-meter-only';
select is(public.api_cancel_quote_request((select request_id from cases where name='cancel-disabled-policy'))->>'canceled','true',
 'disabled free policy still allows authoritative cancellation');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='cancel-disabled-policy')),
 'released','valid cancellation settles even after policy disable');
update private.free_quote_policies set enabled=true where revision='synthetic-meter-only';

insert into cases values('rollback',free_meter_fixture.new_request());
select throws_ok(format('select public.reconcile_vendor_quote_offers(%L::uuid,%L::jsonb,%L::jsonb)',
 free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),
 jsonb_set(free_meter_fixture.offers(request_id),'{0,supplier}','null'::jsonb)),
 '23502',null,'invalid canonical offer rolls back entire write') from cases where name='rollback';
select is((select status::text from public.vendor_quote_results where id=free_meter_fixture.result_id((select request_id from cases where name='rollback'))),'queued','failed offer mutation rolls back parent status');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from cases where name='rollback')),'reserved','failed offer write retains hold');
select throws_ok($$update private.quote_access_admissions set admission_source='commercial_entitlement' where state='reserved'$$,'P0001','quote_access_admission_immutable','admitted source cannot be rewritten');
select is((select count(*)::integer from public.spend_ledger where organization_id=(select organization_id from free_meter_fixture.context)),
 (select count(*)::integer from free_meter_fixture.spend_before),'all known and pending attempted-spend rows survive quota outcomes');
select ok(not exists(select 1 from free_meter_fixture.spend_before expected left join public.spend_ledger actual on actual.id=expected.id
 where to_jsonb(actual) is distinct from expected.original_row),'success failure cancellation preserve exact costs settlement state and lineage');
select * from finish();
rollback;
