-- Generated by scripts/generate-free-quote-fixtures.mjs; do not edit.
-- Source: scripts/qualification/free-quote-terminal-lifecycle.sql SHA-256 8f8a07e36a9c4af8f5dd67aabf90d3c60c9332cc1a461ac019f04e7ad99f53f1
\set ON_ERROR_STOP on
set search_path=public,extensions;
set statement_timeout='45s';
set lock_timeout='5s';
-- AUTHORED, NOT EXECUTED. Apply the CLI-generated lifecycle migration to an owned disposable
-- full-schema fixture first. This suite rolls back all synthetic rows.
begin;
select no_plan();
\set meter_fixture_limit 20
-- BEGIN exact include supabase/tests/fixtures/free_quote_meter_setup.inc SHA-256 3f35533f003968c89d74198812be3bbd10ad7c636820fd0143f0bf6c87f937d8
-- Synthetic fixture only; execute in an isolated disposable database.
create schema free_meter_fixture;
create function free_meter_fixture.set_identity(p_user_id uuid)
returns void
language plpgsql
set search_path = pg_catalog
as $$
begin
  perform pg_catalog.set_config(
    'request.jwt.claims',
    pg_catalog.jsonb_build_object(
      'sub', p_user_id,
      'role', 'authenticated', -- NOSONAR: repeated authenticated JWT fixture claim
      'aal', 'aal1'
    )::text,
    true
  );
  perform pg_catalog.set_config('request.jwt.claim.sub', p_user_id::text, true);
  perform pg_catalog.set_config('request.jwt.claim.role', 'authenticated', true);
end;
$$;

create table free_meter_fixture.context (
  user_id uuid not null,
  organization_id uuid not null,
  job_id uuid not null,
  part_id uuid not null,
  approval_reference uuid not null,
  scope_fingerprint text,
  rollback_scope_fingerprint text,
  quote_run_id uuid
);

insert into free_meter_fixture.context values (
  '00000000-0000-4000-8000-000000008811',
  '00000000-0000-4000-8000-000000008812',
  '00000000-0000-4000-8000-000000008813',
  '00000000-0000-4000-8000-000000008814',
  '00000000-0000-4000-8000-000000008815',
  null,
  null,
  null
);

grant select, update on free_meter_fixture.context to authenticated;

insert into auth.users (id, aud, role, email, email_confirmed_at)
values (
  (select user_id from free_meter_fixture.context),
  'authenticated',
  'authenticated',
  'free-meter-member@example.test',
  timezone('utc', now())
);

insert into public.organizations (id, name, slug)
values (
  (select organization_id from free_meter_fixture.context),
  'Free meter Dispatch',
  'free-meter-dispatch'
);

insert into public.organization_memberships (organization_id, user_id, role)
select organization_id, user_id, 'client'
from free_meter_fixture.context;

-- This dispatch fixture starts after an administrator confirmed its destination.
update public.organizations set shipping_same_as_billing=false, shipping_street='123 Fixture Ave',
  shipping_city='Tucson', shipping_state='AZ', shipping_zip='85701', shipping_country='US'
where id=(select organization_id from free_meter_fixture.context);
insert into private.sourcing_destination_history (organization_id, state, address)
select organization_id, 'confirmed', private.effective_sourcing_address(organization_id) from free_meter_fixture.context;

update private.commercial_rollout_controls
set enabled = true,
    revision = revision + 1,
    change_reason = 'Free-meter local pgTAP fixture'
where capability = 'automatic_quote_collection'; -- NOSONAR: canonical rollout capability fixture is exercised across preflight states

insert into public.jobs (
  id, organization_id, created_by, title, status,
  requested_service_kinds, primary_service_kind
)
select job_id, organization_id, user_id, 'Free-meter validation part',
  'ready_to_quote', array['manufacturing_quote'], 'manufacturing_quote' -- NOSONAR: deterministic quote-envelope fixture
from free_meter_fixture.context;

insert into public.jobs (
  id, organization_id, created_by, title, status,
  requested_service_kinds, primary_service_kind
)
select '00000000-0000-4000-8000-000000008821', organization_id, user_id, -- NOSONAR: deterministic fixture identifier
  'Free-meter rollback part', 'ready_to_quote',
  array['manufacturing_quote'], 'manufacturing_quote'
from free_meter_fixture.context;

insert into public.organization_file_blobs (
  id, organization_id, content_sha256, trusted_content_sha256,
  storage_bucket, storage_path, size_bytes, mime_type
)
select
  '00000000-0000-4000-8000-000000008816', organization_id,
  repeat('a', 64), repeat('a', 64), 'job-files', -- NOSONAR: deterministic trusted-file hash and bucket fixture
  organization_id::text || '/sha256/' || repeat('a', 64) || '/part.step', -- NOSONAR: deterministic trusted storage path
  100, 'application/step' -- NOSONAR: canonical STEP MIME fixture
from free_meter_fixture.context;

insert into public.job_files (
  id, job_id, organization_id, uploaded_by, blob_id, content_sha256,
  trusted_content_sha256, storage_bucket, storage_path, original_name,
  normalized_name, file_kind, mime_type, size_bytes
)
select
  '00000000-0000-4000-8000-000000008817', job_id, organization_id, -- NOSONAR: deterministic fixture identifier
  user_id, '00000000-0000-4000-8000-000000008816', repeat('a', 64),
  repeat('a', 64), 'job-files',
  organization_id::text || '/sha256/' || repeat('a', 64) || '/part.step',
  'part.step', 'part', 'cad', 'application/step', 100
from free_meter_fixture.context;

insert into public.parts (
  id, job_id, organization_id, name, normalized_key, cad_file_id, quantity
)
select part_id, job_id, organization_id, 'Validation part', 'validation-part',
  '00000000-0000-4000-8000-000000008817', 1
from free_meter_fixture.context;

insert into public.approved_part_requirements (
  part_id, organization_id, approved_by, material, finish,
  tightest_tolerance_inch, quantity, quote_quantities,
  applicable_vendors, spec_snapshot
)
select part_id, organization_id, user_id, '6061-T6 Aluminum', 'As machined', -- NOSONAR: canonical controlled-beta material and finish fixture
  0.0050, 1, array[1], array['xometry']::public.vendor_name[], -- NOSONAR: canonical tolerance, quantity, provider, and transport-scale fixture
  '{"process":"CNC milling","tightestToleranceInch":0.0050}'::jsonb -- NOSONAR: canonical process and transport-scale fixture
from free_meter_fixture.context;


-- Synthetic fixtures only: no production allowance or enrollment selected.
insert into private.founding_beta_enrollment_events(organization_id,actor_user_id,action,reason,policy_revision,terms_path,privacy_path,idempotency_key)
select organization_id,user_id,'grant','free access fixture','founding-beta-2026-08-15','/legal/beta-terms','/legal/privacy','free-access-grant' from free_meter_fixture.context;
insert into private.founding_beta_notice_acceptances(organization_id,user_id,policy_revision,terms_path,privacy_path)
select organization_id,user_id,'founding-beta-2026-08-15','/legal/beta-terms','/legal/privacy' from free_meter_fixture.context;
insert into public.org_vendor_configs(organization_id,vendor,enabled_for_client_quote_requests)
select organization_id,'xometry',true from free_meter_fixture.context;


-- Keep the pre-existing request/spend guards enabled; explicit larger fixture
-- settings let this one SQL test exercise independent cases without choosing a
-- production allowance or removing any admission check.
insert into public.quote_request_guardrails(organization_id,user_max_requests_per_window,org_pending_cost_ceiling_usd)
select organization_id,100,100000 from free_meter_fixture.context;
insert into private.free_quote_policies(revision,enabled,subject_kind,completed_limit,window_start,window_end)
values ('synthetic-meter-only',true,'organization',:meter_fixture_limit,clock_timestamp()-interval '1 minute',clock_timestamp()+interval '1 hour');

create table free_meter_fixture.spend_before(id uuid primary key, original_row jsonb not null);

create function free_meter_fixture.new_request()
returns uuid language plpgsql as $$
declare
 v_user uuid; v_org uuid; v_job uuid:=gen_random_uuid(); v_part uuid:=gen_random_uuid();
 v_file uuid:=gen_random_uuid(); v_scope jsonb; v_response jsonb;
begin
 select user_id,organization_id into v_user,v_org from free_meter_fixture.context;
 perform free_meter_fixture.set_identity(v_user);
 insert into public.jobs(id,organization_id,created_by,title,status,requested_service_kinds,primary_service_kind)
 values(v_job,v_org,v_user,'Synthetic meter case','ready_to_quote',array['manufacturing_quote'],'manufacturing_quote');
 insert into public.job_files(id,job_id,organization_id,uploaded_by,blob_id,content_sha256,trusted_content_sha256,
 storage_bucket,storage_path,original_name,normalized_name,file_kind,mime_type,size_bytes)
 select v_file,v_job,organization_id,uploaded_by,blob_id,content_sha256,trusted_content_sha256,
 storage_bucket,storage_path,'case.step','case','cad',mime_type,size_bytes from public.job_files
 where id='00000000-0000-4000-8000-000000008817';
 insert into public.parts(id,job_id,organization_id,name,normalized_key,cad_file_id,quantity)
 values(v_part,v_job,v_org,'Meter part','meter-part',v_file,1);
 insert into public.approved_part_requirements(part_id,organization_id,approved_by,material,finish,
 tightest_tolerance_inch,quantity,quote_quantities,applicable_vendors,spec_snapshot)
 values(v_part,v_org,v_user,'6061-T6 Aluminum','As machined',0.005,1,array[1],array['xometry']::public.vendor_name[],
 '{"process":"CNC milling","tightestToleranceInch":0.0050}'::jsonb);
 v_scope:=public.api_get_xometry_beta_dispatch_scope(v_job,'inch');
 v_response:=public.api_request_xometry_beta_dispatch(v_job,'inch',v_scope->>'scopeFingerprint',
 'founding-beta-2026-08-15',gen_random_uuid(),true,true,true);
 if (v_response->>'accepted')::boolean is not true then raise exception 'fixture admission failed: %',v_response->>'reasonCode'; end if;
 -- Synthetic accounting observations, not charges: prove quota outcomes never
 -- discard attempted known or unresolved spend for this exact run.
 with inserted as (
   insert into public.spend_ledger(organization_id,category,amount_usd,settled,settled_at,job_id,quote_run_id,metadata)
   values (v_org,'vendor_automation',0.025,true,clock_timestamp(),v_job,(v_response->>'quoteRunId')::uuid,'{"fixture":"free-meter-known"}'::jsonb),
          (v_org,'llm_extraction',0.5,false,null,v_job,(v_response->>'quoteRunId')::uuid,'{"fixture":"free-meter-pending"}'::jsonb)
   returning *
 ) insert into free_meter_fixture.spend_before select id,to_jsonb(inserted) from inserted;
 return (v_response->>'quoteRequestId')::uuid;
end;
$$;
create function free_meter_fixture.result_id(p_request uuid)
returns uuid language sql as $$ select vendor_quote_result_id from private.xometry_beta_dispatch_permits where quote_request_id=p_request $$;
create function free_meter_fixture.offers(p_request uuid,p_price numeric default 12,p_valid_until timestamptz default clock_timestamp()+interval '1 day',p_provenance text default 'trusted_adapter')
returns jsonb language sql as $$
 select jsonb_build_array(jsonb_build_object('vendor_quote_result_id',permit.vendor_quote_result_id,
 'organization_id',permit.organization_id,'offer_key','fixture-offer','supplier','Xometry','lane_label','Fixture',
 'geographic_origin','unknown','quoted_at',clock_timestamp()-interval '1 minute','valid_until',p_valid_until,
 'validity_source','vendor_date','provenance_status',p_provenance,'unit_price_usd',p_price,'total_price_usd',p_price,
 'sort_rank',0,'raw_payload','{}'::jsonb)) from private.xometry_beta_dispatch_permits permit where quote_request_id=p_request
$$;
create function free_meter_fixture.result_payload(p_status text default 'instant_quote_received')
returns jsonb language sql as $$ select jsonb_build_object('status',p_status,'unit_price_usd',12,'total_price_usd',12,
 'notes','[]'::jsonb,'dfm_issues','[]'::jsonb,'raw_payload','{}'::jsonb) $$;

-- END exact include supabase/tests/fixtures/free_quote_meter_setup.inc

select ok(not has_function_privilege('anon','public.api_reconcile_terminal_free_quote_tasks(uuid,integer)','EXECUTE'),'anonymous reconciliation forbidden');
select ok(not has_function_privilege('authenticated','public.api_reconcile_terminal_free_quote_tasks(uuid,integer)','EXECUTE'),'customer reconciliation forbidden');
select ok(has_function_privilege('service_role','public.api_reconcile_terminal_free_quote_tasks(uuid,integer)','EXECUTE'),'service-only bounded reconciliation');
select ok(not has_function_privilege('service_role','private.fence_reserved_free_quote_job_delete()','EXECUTE'),'no direct delete-fence authority');
set local role authenticated;
select throws_ok($$select public.api_reconcile_terminal_free_quote_tasks()$$,'42501',null,'actual customer invocation rejected');
reset role;
set local role service_role;
select lives_ok($$select public.api_reconcile_terminal_free_quote_tasks()$$,'actual service invocation succeeds without direct receipt permissions');
reset role;
select throws_ok($$select public.api_reconcile_terminal_free_quote_tasks(null,101)$$,'P0001','free_quote_reconciliation_limit_invalid','unbounded batch rejected');

create temporary table lifecycle_cases(name text primary key,request_id uuid not null,job_id uuid);
insert into lifecycle_cases(name,request_id) values
 ('crash',free_meter_fixture.new_request()),('retry',free_meter_fixture.new_request()),
 ('success',free_meter_fixture.new_request()),('cancel',free_meter_fixture.new_request()),
 ('delete',free_meter_fixture.new_request()),('revived',free_meter_fixture.new_request());
update lifecycle_cases c set job_id=a.job_id from private.quote_access_admissions a where a.quote_request_id=c.request_id;

-- Simulate the durable queue write from a crashed-worker reap. The scan runs in
-- a separate call and must also recover an interruption before that call.
update public.work_queue set status='failed',locked_at=null,locked_by=null,last_error='worker_crash_recovery'
where id=(select p.work_queue_task_id from private.xometry_beta_dispatch_permits p
 join lifecycle_cases c on c.request_id=p.quote_request_id where c.name='crash');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='crash')),'reserved','queue-only terminal write leaves recoverable hold');
select public.api_reconcile_terminal_free_quote_tasks();
select is((select status::text from public.vendor_quote_results where id=free_meter_fixture.result_id((select request_id from lifecycle_cases where name='crash'))),'failed','reconciliation terminalizes the pinned result');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='crash')),'released','crash releases free capacity');
select is((public.api_reconcile_terminal_free_quote_tasks()->>'reconciled')::integer,0,'repeat scan does not double-settle');
select throws_ok(format('select public.reconcile_vendor_quote_offers(%L::uuid,%L::jsonb,%L::jsonb)',
 free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id)),
 'P0001','free_quote_terminal_fenced','late success cannot resurrect released task') from lifecycle_cases where name='crash';
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='retry')),'reserved','queued retry remains reserved');

-- Terminal-looking task with a still-active lease is not an eligible settlement.
update public.work_queue set status='failed',locked_at=clock_timestamp(),locked_by='synthetic-worker'
where id=(select p.work_queue_task_id from private.xometry_beta_dispatch_permits p
 join lifecycle_cases c on c.request_id=p.quote_request_id where c.name='revived');
select public.api_reconcile_terminal_free_quote_tasks();
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='revived')),'reserved','uncleared lease is deferred');
update public.work_queue set status='running' where id=(select p.work_queue_task_id from private.xometry_beta_dispatch_permits p
 join lifecycle_cases c on c.request_id=p.quote_request_id where c.name='revived');
select public.api_reconcile_terminal_free_quote_tasks();
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='revived')),'reserved','revived running task is untouched');

select public.reconcile_vendor_quote_offers(free_meter_fixture.result_id(request_id),free_meter_fixture.result_payload(),free_meter_fixture.offers(request_id))
from lifecycle_cases where name='success';
update public.work_queue set status='failed',locked_at=null,locked_by=null where id=(select p.work_queue_task_id from private.xometry_beta_dispatch_permits p
 join lifecycle_cases c on c.request_id=p.quote_request_id where c.name='success');
select public.api_reconcile_terminal_free_quote_tasks();
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='success')),'consumed','success before cleanup failure remains consumed exactly once');
select is((select status::text from public.vendor_quote_results where id=free_meter_fixture.result_id((select request_id from lifecycle_cases where name='success'))),'instant_quote_received','canonical success is not overwritten');
select public.api_cancel_quote_request(request_id) from lifecycle_cases where name='cancel';
select public.api_reconcile_terminal_free_quote_tasks();
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='cancel')),'released','canceled receipt remains released');

-- No lifecycle reconciliation may change any attempted cost observation.
select ok(not exists(select 1 from free_meter_fixture.spend_before expected left join public.spend_ledger actual on actual.id=expected.id
 where to_jsonb(actual) is distinct from expected.original_row),'reconciliation preserves every known and unresolved spend row exactly');

update public.jobs set archived_at=clock_timestamp() where id in(select job_id from lifecycle_cases);
select throws_ok(format('select public.api_delete_archived_jobs(array[%L::uuid])',job_id),'P0001','free_quote_reservation_unresolved',
 'archived reserved job cannot be deleted') from lifecycle_cases where name='delete';
select ok(exists(select 1 from public.jobs where id=(select job_id from lifecycle_cases where name='delete')),'rejected delete preserves job and canonical identity');
select public.api_cancel_quote_request(request_id) from lifecycle_cases where name='delete';
select lives_ok(format('select public.api_delete_archived_jobs(array[%L::uuid])',job_id),'settled released job may be deleted') from lifecycle_cases where name='delete';
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='delete')),'released','released historical receipt survives deletion');
select lives_ok(format('select public.api_delete_archived_jobs(array[%L::uuid])',job_id),'consumed job may be deleted') from lifecycle_cases where name='success';
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='success')),'consumed','consumed history survives deletion');
select is((select count(*)::integer from public.spend_ledger where id in(select id from free_meter_fixture.spend_before)),
 (select count(*)::integer from free_meter_fixture.spend_before),'historical attempted costs survive job deletion');

-- Forged task metadata cannot redirect settlement; immutable permit IDs win.
insert into lifecycle_cases(name,request_id) values('forged-task',free_meter_fixture.new_request());
update public.work_queue set status='failed',locked_at=null,locked_by=null,part_id=null
where id=(select p.work_queue_task_id from private.xometry_beta_dispatch_permits p
 join lifecycle_cases c on c.request_id=p.quote_request_id where c.name='forged-task');
select ok((public.api_reconcile_terminal_free_quote_tasks()->>'indeterminate')::integer>0,'forged binding emits bounded diagnostic');
select is((select state from private.quote_access_admissions where quote_request_id=(select request_id from lifecycle_cases where name='forged-task')),'reserved','forged binding retains hold for investigation');
select is((select status::text from public.vendor_quote_results where id=free_meter_fixture.result_id((select request_id from lifecycle_cases where name='forged-task'))),'queued','forged binding cannot mutate unrelated result');

-- Nullable job and lane-result fields must also fail closed (SQL NULL is not false).
insert into lifecycle_cases(name,request_id) values('null-job',free_meter_fixture.new_request()),('null-lane-result',free_meter_fixture.new_request());
update public.work_queue set status='failed',locked_at=null,locked_by=null,job_id=null
where id=(select p.work_queue_task_id from private.xometry_beta_dispatch_permits p
 join lifecycle_cases c on c.request_id=p.quote_request_id where c.name='null-job');
update public.work_queue set status='failed',locked_at=null,locked_by=null
where id=(select p.work_queue_task_id from private.xometry_beta_dispatch_permits p
 join lifecycle_cases c on c.request_id=p.quote_request_id where c.name='null-lane-result');
update public.quote_request_lanes set vendor_quote_result_id=null
where quote_request_id=(select request_id from lifecycle_cases where name='null-lane-result');
select public.api_reconcile_terminal_free_quote_tasks();
select is((select count(*)::integer from private.quote_access_admissions where state='reserved'
 and quote_request_id in(select request_id from lifecycle_cases where name in('null-job','null-lane-result'))),2,'null bindings retain holds');
select is((select count(*)::integer from public.vendor_quote_results where status='queued'
 and id in(select free_meter_fixture.result_id(request_id) from lifecycle_cases where name in('null-job','null-lane-result'))),2,'null bindings cannot terminalize results');

select * from finish();
rollback;
