/** Opt-in checks on an already admitted disposable runtime. No provisioning or env reads. */
import { request } from 'node:https';
import { randomUUID, createHash } from 'node:crypto';
import { createNativePrivateStorage } from '../server/engineering/native-private-storage.ts';
import type { PrivateArtifactSql, ArtifactStorageObject } from '../server/engineering/native-artifact-repository.ts';

export type StorageFixtureAdmission = Readonly<{
  owner: string; fixtureId: string; expiresAt: string;
  storageOrigin: string; databaseOrigin: string; bucket: string;
  imageDigest: string; sourceSha: string;
  containers: readonly string[]; network: string;
  syntheticOnly: true; exclusiveInternalNetwork: true; existingPrivateBucket: true;
}>;
type Status = 'PASS' | 'FAIL' | 'NOT_RUN';
export type StorageQualificationReceipt = {
  admission: StorageFixtureAdmission; sourceSha: string; fixtureId: string; imageDigest: string; startedAt: string;
  mode: 'plan' | 'execute'; checks: Record<string, Status>;
  attemptedObjects: string[]; cleanup: 'NOT_REQUIRED' | 'OWNER_CLEANUP_REQUIRED';
  runtimeIdentity: 'OWNER_ATTESTED_UNVERIFIED'; native: 'NOT_RUN'; overall: 'NOT_QUALIFIED';
};
const names = ['admissionShape', 'privateBucket', 'emptyOwnedTarget', 'createOnlyRace',
  'metadataReference', 'exactVersionHttps', 'missingAuthDenied', 'wrongAuthDenied', 'wrongVersionDenied',
  'crossObjectVersionDenied', 'changedByteReplayPreservesOriginal', 'productDriverExactRead',
  'productDriverCreateConflict', 'staleVersionDenied', 'generationChangesDuringRead',
  'responseLossReplay', 'redirectCompressionPartialTimeout', 'artifactRouteHttps'];
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
function assert(value: unknown): asserts value { if (!value) throw new Error('Fixture qualification check failed.'); }
export function validateStorageFixtureAdmission(a: StorageFixtureAdmission, now = Date.now()) {
  const keys = ['owner', 'fixtureId', 'expiresAt', 'storageOrigin', 'databaseOrigin', 'bucket',
    'imageDigest', 'sourceSha', 'containers', 'network', 'syntheticOnly', 'exclusiveInternalNetwork', 'existingPrivateBucket'];
  assert(Object.keys(a).length === keys.length && Object.keys(a).every(key => keys.includes(key)));
  const storage = new URL(a.storageOrigin), database = new URL(a.databaseOrigin);
  for (const url of [storage, database]) {
    assert(url.hostname === '127.0.0.1' && url.port && !url.username && !url.password
      && url.pathname === '/' && !url.search && !url.hash);
  }
  assert(storage.protocol === 'https:' && database.protocol === 'postgresql:');
  assert(uuid.test(a.fixtureId) && /^[a-zA-Z0-9_-]{1,80}$/.test(a.owner)
    && /^jarvis-fixture-[a-z0-9-]{1,60}$/.test(a.bucket));
  assert(/^sha256:[a-f0-9]{64}$/.test(a.imageDigest) && /^[a-f0-9]{40}$/.test(a.sourceSha));
  assert(a.syntheticOnly === true && a.exclusiveInternalNetwork === true && a.existingPrivateBucket === true);
  assert(a.containers.length > 0 && a.containers.length <= 2 && new Set(a.containers).size === a.containers.length
    && a.containers.every(id => /^[a-f0-9]{64}$/.test(id)) && /^[a-f0-9]{64}$/.test(a.network));
  const remaining = Date.parse(a.expiresAt) - now;
  assert(Number.isFinite(remaining) && remaining > 0 && remaining <= 30 * 60 * 1000);
}

/** Uses direct IPv4 HTTPS and normal certificate/name validation, never global fetch or redirects.
 * ca is a separately admitted EXISTING fixture trust chain, never generated by this runner. */
function fixtureFetch(origin: string, ca: string | undefined): typeof fetch {
  return async (input, init) => {
    const url = new URL(String(input));
    assert(url.origin === origin && url.hostname === '127.0.0.1');
    assert(init?.method === 'GET' || init?.method === 'POST');
    return new Promise<Response>((resolve, reject) => {
      const headers = Object.fromEntries(new Headers(init.headers).entries());
      const req = request(url, { method: init.method, headers, ca, rejectUnauthorized: true,
        signal: init.signal ?? undefined, timeout: 10000 }, res => {
        const chunks: Buffer[] = []; let size = 0;
        res.on('data', (chunk: Buffer) => {
          size += chunk.length;
          if (size > 16000000) { req.destroy(new Error('Fixture response exceeds bound.')); return; }
          chunks.push(chunk);
        });
        res.on('error', reject);
        res.on('aborted', () => reject(new Error('Fixture response aborted.')));
        res.on('end', () => {
          const resultHeaders = new Headers();
          for (const [key, value] of Object.entries(res.headers)) if (value !== undefined)
            resultHeaders.set(key, Array.isArray(value) ? value.join(', ') : value);
          try {
            assert(res.statusCode && res.statusCode >= 200 && res.statusCode <= 599);
            resolve(new Response([204, 205, 304].includes(res.statusCode) ? null : Buffer.concat(chunks),
              { status: res.statusCode, headers: resultHeaders }));
          } catch (error) { reject(error); }
        });
      });
      const deadline = setTimeout(() => req.destroy(new Error('Fixture request deadline.')), 10000);
      req.once('close', () => clearTimeout(deadline));
      req.on('timeout', () => req.destroy(new Error('Fixture request timeout.')));
      req.on('error', reject);
      if (init.body !== undefined) { assert(init.body instanceof Uint8Array); req.write(init.body); }
      req.end();
    });
  };
}

/** sql must be the existing owner-admitted SQL capability for databaseOrigin. The owner is
 * responsible for binding it to that endpoint; an arbitrary function cannot prove its origin.
 * Plan mode does not inspect capabilities or authorization. No delete/update SQL or HTTP exists. */
export async function qualifyNativeStorage(options: {
  admission: StorageFixtureAdmission; execute?: boolean;
  capabilities?: { sql: PrivateArtifactSql; authorization: string; existingCaPem?: string;
    persistCheckpoint: (receipt: StorageQualificationReceipt) => Promise<void> };
}): Promise<StorageQualificationReceipt> {
  const a = structuredClone(options.admission);
  const receipt: StorageQualificationReceipt = {
    admission: structuredClone(a), sourceSha: a.sourceSha, fixtureId: a.fixtureId, imageDigest: a.imageDigest,
    startedAt: new Date().toISOString(), mode: options.execute === true ? 'execute' : 'plan',
    checks: Object.fromEntries(names.map(name => [name, 'NOT_RUN'])), attemptedObjects: [],
    cleanup: 'NOT_REQUIRED', runtimeIdentity: 'OWNER_ATTESTED_UNVERIFIED', native: 'NOT_RUN', overall: 'NOT_QUALIFIED',
  };
  validateStorageFixtureAdmission(a);
  if (options.execute !== true) return receipt;
  const capability = options.capabilities;
  assert(capability && typeof capability.persistCheckpoint === 'function' && /^Bearer [^\r\n]{1,16000}$/.test(capability.authorization));
  const sql = capability.sql, authorization = capability.authorization;
  const fetch = fixtureFetch(new URL(a.storageOrigin).origin, capability.existingCaPem);
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), Math.min(120000, Date.parse(a.expiresAt) - Date.now()));
  const signal = controller.signal;
  const bounded = <T>(work: () => Promise<T>) => new Promise<T>((resolve, reject) => {
    const cleanup = () => { clearTimeout(capabilityTimer); signal.removeEventListener('abort', stop); };
    const stop = () => { cleanup(); reject(new Error('Fixture capability expired.')); };
    if (signal.aborted) { reject(new Error('Fixture capability expired.')); return; }
    const capabilityTimer = setTimeout(stop, 10000);
    signal.addEventListener('abort', stop, { once: true });
    Promise.resolve().then(() => { assert(!signal.aborted); return work(); }).then(resolve, reject).finally(cleanup);
  });
  const query = (text: string, values: readonly unknown[]) => bounded(() => sql.query(text, values, { signal, timeoutMs: 30000 }));
  const checkpoint = () => bounded(() => capability.persistCheckpoint(structuredClone(receipt)));
  const target = `qualification/${a.fixtureId}/${randomUUID()}`;
  const bytes = new TextEncoder().encode(`JARVIS synthetic Storage qualification ${a.fixtureId}\n`);
  const changed = new TextEncoder().encode('SYNTHETIC CHANGED REPLAY MUST NOT REPLACE\n');
  const equal = async (response: Response, expected: Uint8Array) => {
    assert(response.status === 200);
    assert(createHash('sha256').update(new Uint8Array(await response.arrayBuffer())).digest('hex')
      === createHash('sha256').update(expected).digest('hex'));
  };
  const objectUrl = (name: string) => `${a.storageOrigin.replace(/\/$/, '')}/storage/v1/object/${a.bucket}/${name}`;
  const get = (name: string, version: string, auth: string | null = authorization) => fetch(
    objectUrl(name).replace('/object/', '/object/authenticated/') + `?versionId=${version}`,
    { method: 'GET', signal, headers: auth === null ? {} : { authorization: auth } });
  const post = (name: string, body = bytes) => fetch(objectUrl(name), {
    method: 'POST', signal, headers: { authorization, 'content-type': 'application/octet-stream', 'x-upsert': 'false' }, body });
  const conflict = async (r: Response) => {
    assert(r.status === 400 || r.status === 409);
    assert((await r.json()).code === 'ResourceAlreadyExists');
  };
  const reference = async (name: string): Promise<ArtifactStorageObject> => {
    const rows = await query(`select o.id as "storageObjectId", o.bucket_id as "bucketId", o.name as "objectName",
      o.version as "storageVersion", o.updated_at::text as "storageUpdatedAt"
      from storage.objects o join storage.buckets b on b.id=o.bucket_id and not b.public
      where o.bucket_id=$1 and o.name=$2`, [a.bucket, name]);
    assert(rows.length === 1 && uuid.test(String(rows[0].storageVersion)));
    return rows[0] as ArtifactStorageObject;
  };
  let active = 'admissionShape';
  const check = async (name: string, work: () => Promise<void>) => {
    active = name; assert(!signal.aborted); await work(); assert(!signal.aborted); receipt.checks[name] = 'PASS';
  };
  try {
    receipt.checks.admissionShape = 'PASS';
    await check('privateBucket', async () => {
      const rows = await query('select id from storage.buckets where id=$1 and not public', [a.bucket]);
      assert(rows.length === 1 && rows[0].id === a.bucket);
    });
    await check('emptyOwnedTarget', async () => {
      const rows = await query('select id from storage.objects where bucket_id=$1 and name in ($2,$3)', [a.bucket, target, target + '-second']);
      assert(rows.length === 0);
    });
    await check('createOnlyRace', async () => {
      receipt.attemptedObjects.push(target); receipt.cleanup = 'OWNER_CLEANUP_REQUIRED';
      await checkpoint();
      const responses = await Promise.all([post(target), post(target)]);
      assert(responses.filter(r => r.ok).length === 1);
      await conflict(responses.find(r => !r.ok)!);
    });
    let ref: ArtifactStorageObject;
    await check('metadataReference', async () => { ref = await reference(target); });
    await check('exactVersionHttps', async () => equal(await get(target, ref.storageVersion), bytes));
    // Require an explicit rejection; an outage/redirect is not authentication proof.
    const denied = async (r: Response) => assert([400, 401, 403, 404].includes(r.status));
    await check('missingAuthDenied', async () => denied(await get(target, ref.storageVersion, null)));
    await check('wrongAuthDenied', async () => denied(await get(target, ref.storageVersion, 'Bearer deliberately-invalid-synthetic-token')));
    await check('wrongVersionDenied', async () => denied(await get(target, randomUUID())));
    await check('crossObjectVersionDenied', async () => {
      receipt.attemptedObjects.push(target + '-second');
      await checkpoint();
      assert((await post(target + '-second')).ok);
      const second = await reference(target + '-second');
      assert(second.storageVersion !== ref.storageVersion);
      await denied(await get(target, second.storageVersion));
    });
    await check('changedByteReplayPreservesOriginal', async () => {
      await conflict(await post(target, changed));
      assert(JSON.stringify(await reference(target)) === JSON.stringify(ref));
      await equal(await get(target, ref.storageVersion), bytes);
    });
    // Scoped test instance only, after raw provider checks; does not mutate deployed qualification flags.
    const driver = createNativePrivateStorage({ sql, storageOrigin: a.storageOrigin, authorization,
      fetch, enabled: true, versionIdQualified: true, timeoutMs: 10000 });
    await check('productDriverExactRead', async () => equal(await driver.read({ ...ref, method: 'GET', ifMatch: ref.storageVersion }, signal), bytes));
    await check('productDriverCreateConflict', async () => assert(await driver.create({ method: 'PUT', ifNoneMatch: '*',
      bucketId: a.bucket, objectName: target, contentType: 'application/octet-stream', bytes: changed }, signal) === 'conflict'));
  } catch { receipt.checks[active] = 'FAIL'; }
  finally { clearTimeout(timer); controller.abort(); }
  return receipt;
}
