-- Seed capability profiles for hidden live-quote vendor candidates.
-- This is separate from the enum-add migration because PostgreSQL cannot use
-- newly added enum values safely until the adding transaction has committed.

insert into public.vendor_capability_profiles (
  vendor_name,
  process_types,
  materials,
  tolerance_min_mm,
  tolerance_max_mm,
  max_part_size_mm,
  min_quantity,
  max_quantity,
  geographic_region,
  certifications,
  quality_score,
  lead_time_reliability,
  cost_competitiveness,
  domestic_us
) values
  (
    'oshcut',
    array['laser_cutting', 'sheet_metal']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel', 'brass', 'copper'],
    0.05,
    0.25,
    3000,
    1,
    null,
    'US',
    array['ISO9001'],
    null,
    null,
    null,
    true
  ),
  (
    'fabworks',
    array['laser_cutting', 'sheet_metal']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel'],
    0.05,
    0.25,
    3000,
    1,
    null,
    'US',
    array[]::text[],
    null,
    null,
    null,
    true
  ),
  (
    'ponoko',
    array['laser_cutting', 'sheet_metal']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel', 'acrylic', 'delrin', 'wood'],
    0.08,
    0.25,
    3000,
    1,
    null,
    'US',
    array[]::text[],
    null,
    null,
    null,
    true
  ),
  (
    'quickparts',
    array['cnc_milling', 'cnc_turning', 'injection_molding', '3d_printing', 'sheet_metal']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel', 'titanium', 'brass', 'abs', 'nylon', 'polycarbonate'],
    0.01,
    0.1,
    1200,
    1,
    null,
    'Global',
    array['ISO9001'],
    null,
    null,
    null,
    false
  ),
  (
    'rapiddirect',
    array['cnc_milling', 'cnc_turning', 'injection_molding', '3d_printing', 'sheet_metal']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel', 'titanium', 'brass', 'abs', 'nylon', 'polycarbonate'],
    0.01,
    0.1,
    1500,
    1,
    null,
    'China',
    array['ISO9001'],
    null,
    null,
    null,
    false
  ),
  (
    'geomiq',
    array['cnc_milling', 'cnc_turning', 'injection_molding', '3d_printing', 'sheet_metal']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel', 'titanium', 'brass', 'abs', 'nylon'],
    0.01,
    0.1,
    1200,
    1,
    null,
    'Global',
    array['ISO9001', 'ISO13485'],
    null,
    null,
    null,
    false
  ),
  (
    'weerg',
    array['cnc_milling', 'cnc_turning', '3d_printing', 'laser_cutting']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel', 'abs', 'nylon'],
    0.01,
    0.1,
    1000,
    1,
    null,
    'EU',
    array['ISO9001'],
    null,
    null,
    null,
    false
  ),
  (
    'protolabsnetwork',
    array['cnc_milling', 'cnc_turning', 'injection_molding', '3d_printing', 'sheet_metal']::public.process_types[],
    array['aluminum', 'steel', 'stainless_steel', 'titanium', 'brass', 'abs', 'nylon', 'polycarbonate'],
    0.01,
    0.1,
    1500,
    1,
    null,
    'Global',
    array['ISO9001'],
    null,
    null,
    null,
    false
  )
on conflict (vendor_name) do update
set
  process_types = excluded.process_types,
  materials = excluded.materials,
  tolerance_min_mm = excluded.tolerance_min_mm,
  tolerance_max_mm = excluded.tolerance_max_mm,
  max_part_size_mm = excluded.max_part_size_mm,
  min_quantity = excluded.min_quantity,
  max_quantity = excluded.max_quantity,
  geographic_region = excluded.geographic_region,
  certifications = excluded.certifications,
  domestic_us = excluded.domestic_us,
  updated_at = timezone('utc', now());
