-- OVD-591: immutable pre-dispatch retention only. No runtime or dispatch authority.
-- Migration basename must be generated by the authorized Supabase CLI owner.
begin;

create sequence private.capability_preparation_cursor_seq as bigint
  minvalue 1 maxvalue 9223372036854775807 start with 1 increment by 1 cache 1 no cycle;
create table private.capability_claim_preparations (
  request_key uuid primary key,
  window_key text not null,
  completion_key uuid not null unique,
  cursor bigint not null unique check (cursor > 0),
  input jsonb not null check (octet_length(input::text) <= 16384)
);
create index capability_claim_preparations_window_cursor
  on private.capability_claim_preparations (window_key, cursor);
create table private.capability_completion_preparations (
  completion_key uuid primary key references private.capability_claim_preparations(completion_key),
  input jsonb not null check (octet_length(input::text) <= 16384)
);
create table private.capability_attention_preparations (
  evaluation_key uuid primary key,
  scope_key text not null,
  cursor bigint not null unique check (cursor > 0),
  input jsonb not null check (octet_length(input::text) <= 16384)
);
create index capability_attention_preparations_scope_cursor
  on private.capability_attention_preparations (scope_key, cursor);

-- Small static validators do not call a mutating runtime RPC. Every invalid shape
-- returns false (including SQL NULL); public entry points sanitize all exceptions.
create function private.capability_preparation_json(p jsonb, depth integer default 0)
returns boolean language plpgsql immutable set search_path = pg_catalog as $$
declare x jsonb; n integer;
begin
  if p is null or depth > 8 then return false; end if;
  case jsonb_typeof(p)
    when 'null', 'boolean' then return true;
    when 'number' then return length(p::text) <= 32;
    when 'string' then return length(p #>> '{}') <= 512;
    when 'array' then
      if jsonb_array_length(p) > 100 then return false; end if;
      for x in select value from jsonb_array_elements(p) loop
        if not private.capability_preparation_json(x, depth + 1) then return false; end if;
      end loop;
    when 'object' then
      select count(*) into n from jsonb_object_keys(p);
      if n > 40 then return false; end if;
      for x in select value from jsonb_each(p) loop
        if not private.capability_preparation_json(x, depth + 1) then return false; end if;
      end loop;
    else return false;
  end case;
  return true;
end $$;
create function private.capability_preparation_string(p jsonb, pattern text)
returns boolean language sql immutable set search_path = pg_catalog as $$
  select coalesce(jsonb_typeof(p) = 'string' and (p #>> '{}') ~ pattern, false)
$$;
create function private.capability_preparation_uuid(p jsonb)
returns boolean language sql immutable set search_path = pg_catalog as $$
  select private.capability_preparation_string(p, '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$')
$$;
create function private.capability_preparation_integer(p jsonb, lo bigint, hi bigint)
returns boolean language sql immutable set search_path = pg_catalog as $$
  select coalesce(jsonb_typeof(p) = 'number' and p::text ~ '^[0-9]+$'
    and (p::text)::numeric between lo and hi, false)
$$;
create function private.capability_preparation_time(p jsonb)
returns boolean language plpgsql immutable set search_path = pg_catalog as $$
declare s text; t timestamptz;
begin
  if not private.capability_preparation_string(p, '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,6})?(Z|[+]00:00)$') then return false; end if;
  s := p #>> '{}'; t := s::timestamptz;
  return to_char(t at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') = left(s, 19);
exception when others then return false;
end $$;
create function private.capability_preparation_tokens(p jsonb, pattern text)
returns boolean language plpgsql immutable set search_path = pg_catalog as $$
begin
  if jsonb_typeof(p) is distinct from 'array' then return false; end if;
  return jsonb_array_length(p) <= 32 and not exists (
    select from jsonb_array_elements(p) x where not private.capability_preparation_string(x, pattern)
  );
end $$;
create function private.capability_preparation_claim_valid(p jsonb)
returns boolean language plpgsql immutable set search_path = pg_catalog as $$
declare r jsonb := p->'request'; k text;
begin
  if not private.capability_runtime_keys(p, array['request','completionKey'])
    or not private.capability_preparation_uuid(p->'completionKey')
    or not private.capability_runtime_keys(r, array['windowKey','resourceKey','configDigest','requestKey','provider','route','surface','surfaceRevision','windowStart','windowEnd','leaseSeconds'])
    or not private.capability_preparation_string(r->'windowKey', '^canary:[a-f0-9]{64}$')
    or not private.capability_preparation_string(r->'resourceKey', '^[a-f0-9]{64}$')
    or not private.capability_preparation_string(r->'configDigest', '^[a-f0-9]{64}$')
    or not private.capability_preparation_uuid(r->'requestKey')
    or not private.capability_preparation_integer(r->'leaseSeconds', 1, 300)
    or not private.capability_preparation_time(r->'windowStart')
    or not private.capability_preparation_time(r->'windowEnd') then return false; end if;
  foreach k in array array['provider','route','surface','surfaceRevision'] loop
    if not private.capability_preparation_string(r->k, '^[a-z][a-z0-9._-]{0,79}$') then return false; end if;
  end loop;
  perform (r->>'provider')::public.vendor_name;
  return (r->>'windowEnd')::timestamptz > (r->>'windowStart')::timestamptz
    and (r->>'windowEnd')::timestamptz - (r->>'windowStart')::timestamptz <= interval '26 hours';
exception when others then return false;
end $$;
create function private.capability_preparation_completion_valid(p jsonb)
returns boolean language plpgsql immutable set search_path = pg_catalog as $$
declare c jsonb := p->'candidate'; k text;
begin
  if not private.capability_runtime_keys(p, array['windowKey','requestKey','fence','completionKey','candidate','resourceReleased'])
    or not private.capability_preparation_string(p->'windowKey', '^canary:[a-f0-9]{64}$')
    or p->'resourceReleased' is distinct from 'true'::jsonb
    or not private.capability_preparation_uuid(p->'requestKey')
    or not private.capability_preparation_uuid(p->'fence')
    or not private.capability_preparation_uuid(p->'completionKey')
    or not private.capability_runtime_keys(c, array['provider','route','surface','revision','state','extensions','mimeTypes','acceptAttributePresent','observedAt','expiresAt','actorKind','sourceKind','sourceVersion','evidenceReference','idempotencyKey']) then return false; end if;
  foreach k in array array['provider','route','surface','revision','sourceVersion'] loop
    if not private.capability_preparation_string(c->k, '^[a-z][a-z0-9._-]{0,79}$') then return false; end if;
  end loop;
  perform (c->>'provider')::public.vendor_name;
  if not private.capability_preparation_string(c->'state', '^(fresh|loading|route_or_selector_drift|authentication_required|anti_bot_or_challenge|provider_error|unclassified_response|ambiguous)$')
    or not private.capability_preparation_tokens(c->'extensions', '^[a-z0-9][a-z0-9_-]{0,31}$')
    or not private.capability_preparation_tokens(c->'mimeTypes', '^[a-z0-9][a-z0-9!#$&^_.+-]{0,126}/[a-z0-9][a-z0-9!#$&^_.+-]{0,126}$')
    or jsonb_typeof(c->'acceptAttributePresent') not in ('boolean','null')
    or not private.capability_preparation_time(c->'observedAt')
    or not private.capability_preparation_time(c->'expiresAt')
    or c->'actorKind' is distinct from '"scheduled_canary"'::jsonb
    or c->'sourceKind' is distinct from '"scheduled_canary"'::jsonb
    or not private.capability_preparation_string(c->'evidenceReference', '^issue:OVD-[1-9][0-9]{0,9}$')
    or c->'idempotencyKey' is distinct from p->'windowKey' then return false; end if;
  return (c->>'expiresAt')::timestamptz > (c->>'observedAt')::timestamptz
    and (c->>'expiresAt')::timestamptz - (c->>'observedAt')::timestamptz <= interval '1 hour'
    and ((c->>'state' = 'fresh' and c->'acceptAttributePresent' <> 'null'::jsonb)
      or (c->>'state' <> 'fresh' and c->'extensions' = '[]'::jsonb and c->'mimeTypes' = '[]'::jsonb and c->'acceptAttributePresent' = 'null'::jsonb));
exception when others then return false;
end $$;

-- Static sanitized attention contract, including the existing canonical field
-- validation. There is deliberately no current-head, lease, CAS or clock lookup.
create function private.capability_preparation_attention_valid(p jsonb)
returns boolean language plpgsql immutable set search_path = pg_catalog as $$
declare c jsonb := p->'cursor'; i jsonb := p->'item'; intent jsonb := p->'intent';
  e jsonb := p->'evidence'; m jsonb; k text; canonical_metadata text;
begin
 if not private.capability_runtime_keys(p,array['expectedVersion','evaluationKey','cursor','item','intent','evidence']) or octet_length(p::text)>16384 then raise exception 'Invalid attention'; end if;
 if jsonb_typeof(p->'expectedVersion') is distinct from 'number' or jsonb_typeof(p->'evaluationKey') is distinct from 'string' then raise exception 'Invalid CAS'; end if;
 perform (p->>'evaluationKey')::uuid;
 if not private.capability_runtime_keys(c,array['scopeKey','fingerprint','generation','lastObservationRevision','lastObservedAt','lastEvidenceHash','evaluatedAt'])
 or not private.capability_runtime_keys(i,array['key','category','metadata','severity','reasonCode','summary','freshness','observedAt','expiresAt','checkedAt','formatCounts','occurrenceCount','firstSeenAt','lastChangedAt','action'])
 then raise exception 'Invalid projection'; end if;
 if exists(select from jsonb_each(c) x where x.value='null'::jsonb and x.key not in ('lastObservationRevision','lastObservedAt','lastEvidenceHash'))
 or exists(select from jsonb_each(i) x where x.value='null'::jsonb and x.key not in ('observedAt','expiresAt','formatCounts','occurrenceCount','firstSeenAt','lastChangedAt','action'))
 or jsonb_typeof(c->'generation') is distinct from 'number'
 or jsonb_typeof(c->'lastObservationRevision') not in ('number','null')
 or jsonb_typeof(c->'lastObservedAt') not in ('string','null') or jsonb_typeof(c->'lastEvidenceHash') not in ('string','null')
 or (c->'lastObservationRevision'<>'null'::jsonb and ((c->>'lastObservationRevision')::bigint not between 1 and 9007199254740991 or c->>'lastEvidenceHash' !~ '^[a-f0-9]{64}$' or c->'lastObservedAt'='null'::jsonb or c->'lastEvidenceHash'='null'::jsonb))
 or (c->'lastObservationRevision'='null'::jsonb and (c->'lastObservedAt'<>'null'::jsonb or c->'lastEvidenceHash'<>'null'::jsonb)) then raise exception 'Invalid cursor'; end if;
 if exists(select from jsonb_each(c) x where (x.key='generation' and jsonb_typeof(x.value)<>'number') or (x.key not in ('generation','lastObservationRevision','lastObservedAt','lastEvidenceHash') and jsonb_typeof(x.value)<>'string')) then raise exception 'Invalid cursor types'; end if;
 m:=i->'metadata';
 if not private.capability_runtime_keys(m,array['provider','route','surface','surfaceRevision','policyRevision','adapterRevision','workerBuild'])
 or exists(select from jsonb_each(m) x where jsonb_typeof(x.value) not in ('string','null'))
 or exists(select from jsonb_each_text(m) x where (x.value is null and x.key not in ('adapterRevision','workerBuild')) or (x.value is not null and x.value !~ '^[a-z][a-z0-9._-]{0,79}$'))
 or c->>'scopeKey' !~ '^[a-f0-9]{64}$' or c->>'fingerprint' !~ '^[a-f0-9]{64}$'
 or i->>'key' <> 'capability:'||(c->>'scopeKey') or i->>'category'<>'provider_upload_capability'
 or i->>'severity' not in ('healthy','attention','blocked','unknown') or i->>'freshness' not in ('current','stale','unknown')
 or i->'action'<>'null'::jsonb or i->'occurrenceCount'<>'null'::jsonb or i->'firstSeenAt'<>'null'::jsonb or i->'lastChangedAt'<>'null'::jsonb
 or i->>'summary' not in ('Upload capability matches the reviewed policy.','Observed upload formats changed and require review.','Upload capability requires operator review.','Upload capability evidence is stale.','Upload capability evidence is missing or invalid.')
 or i->>'reasonCode' not in ('matches_policy','format_added','format_removed','reviewed_missing_accept_xometry','accept_missing','unsupported','denied','observation_missing','observation_stale','formats_loading','ambiguous_input','route_or_selector_drift','authentication_required','anti_bot_or_challenge','provider_error','unclassified_response','source_malformed')
 or (c->>'generation')::bigint not between 0 and 1000000 or (p->>'expectedVersion')::bigint not between 0 and 9007199254740990
 or i->>'checkedAt'<>c->>'evaluatedAt' then raise exception 'Invalid projection'; end if;
 if i->'formatCounts'<>'null'::jsonb and exists(select from jsonb_each(i->'formatCounts') x where jsonb_typeof(x.value)<>'number') then raise exception 'Invalid count types'; end if;
 if i->'formatCounts'<>'null'::jsonb and (not private.capability_runtime_keys(i->'formatCounts',array['allowed','added','removed']) or exists(select from jsonb_each_text(i->'formatCounts') x where x.value !~ '^[0-9]{1,2}$' or x.value::int>32)) then raise exception 'Invalid counts'; end if;
 if e<>'null'::jsonb then
 if jsonb_typeof(e->'observationRevision') is distinct from 'number' or exists(select from jsonb_each(e) x where x.value='null'::jsonb) then raise exception 'Null evidence'; end if;
 if not private.capability_runtime_keys(e,array['decision','observedAt','expiresAt','observationRevision'])
 or not private.capability_runtime_keys(e->'decision',array['contractVersion','classification','allowedExtensions','reportedAddedExtensions','reportedRemovedExtensions','evidenceRefs','normalizedObservedMimeTypes'])
 or e->'decision'->>'contractVersion'<>'provider-upload-capability.v1'
 or e->'decision'->>'classification' not in ('matches_policy','format_added','format_removed','reviewed_missing_accept_xometry','accept_missing','unsupported','denied','observation_missing','observation_stale','formats_loading','ambiguous_input','route_or_selector_drift','authentication_required','anti_bot_or_challenge','provider_error','unclassified_response')
 or (e->>'observationRevision')::bigint is distinct from (c->>'lastObservationRevision')::bigint
 or (e->>'observedAt')::timestamptz is distinct from (c->>'lastObservedAt')::timestamptz
 or (e->>'expiresAt')::timestamptz <= (e->>'observedAt')::timestamptz
 or (e->>'expiresAt')::timestamptz-(e->>'observedAt')::timestamptz>interval '26 hours'
 then raise exception 'Invalid evidence'; end if;
 if exists(select from jsonb_each(e->'decision') x where x.value='null'::jsonb) then raise exception 'Null decision'; end if;
 foreach k in array array['allowedExtensions','reportedAddedExtensions','reportedRemovedExtensions','evidenceRefs','normalizedObservedMimeTypes'] loop
  if jsonb_typeof(e->'decision'->k)<>'array' or exists(select from jsonb_array_elements(e->'decision'->k) x where jsonb_typeof(x)<>'string') or jsonb_array_length(e->'decision'->k)>32 or exists(select from jsonb_array_elements_text(e->'decision'->k) x where x !~ case when k='evidenceRefs' then '^issue:OVD-[1-9][0-9]{0,9}$' when k='normalizedObservedMimeTypes' then '^[a-z0-9][a-z0-9!#$&^_.+-]{0,126}/[a-z0-9][a-z0-9!#$&^_.+-]{0,126}$' else '^[a-z0-9][a-z0-9_-]{0,31}$' end) then raise exception 'Invalid evidence tokens'; end if;
 end loop;
 end if;
 if intent<>'null'::jsonb and exists(select from jsonb_each(intent) x where x.value='null'::jsonb or (x.key='generation' and jsonb_typeof(x.value)<>'number') or (x.key<>'generation' and jsonb_typeof(x.value)<>'string')) then raise exception 'Invalid intent types'; end if;
 if intent<>'null'::jsonb and (not private.capability_runtime_keys(intent,array['key','itemKey','generation','kind','reasonCode']) or intent->>'key' !~ '^[a-f0-9]{64}$' or intent->>'itemKey'<>i->>'key' or intent->>'generation'<>c->>'generation' or intent->>'kind' not in ('attention','recovery') or intent->>'reasonCode'<>i->>'reasonCode') then raise exception 'Invalid intent'; end if;

 -- The canonical RPC's text extraction is complemented by strict JSON scalar
 -- types here, preventing coercible but unsanitized retained payloads.
 if not private.capability_preparation_uuid(p->'evaluationKey')
   or not private.capability_preparation_integer(p->'expectedVersion', 0, 9007199254740990)
   or not private.capability_preparation_integer(c->'generation', 0, 1000000)
   or not private.capability_preparation_time(c->'evaluatedAt') then return false; end if;
 foreach k in array array['key','category','severity','reasonCode','summary','freshness','checkedAt'] loop
   if jsonb_typeof(i->k) is distinct from 'string' then return false; end if;
 end loop;
 foreach k in array array['observedAt','expiresAt'] loop
   if i->k <> 'null'::jsonb and not private.capability_preparation_time(i->k) then return false; end if;
 end loop;
 if c->'lastObservationRevision' <> 'null'::jsonb and
   (not private.capability_preparation_integer(c->'lastObservationRevision', 1, 9007199254740991)
    or not private.capability_preparation_time(c->'lastObservedAt')
    or (c->>'lastObservedAt')::timestamptz > (c->>'evaluatedAt')::timestamptz) then return false; end if;
 if i->'formatCounts' <> 'null'::jsonb then
   foreach k in array array['allowed','added','removed'] loop
     if not private.capability_preparation_integer(i->'formatCounts'->k, 0, 32) then return false; end if;
   end loop;
 end if;
 if intent <> 'null'::jsonb and not private.capability_preparation_integer(intent->'generation', 0, 1000000) then return false; end if;
 -- Metadata tokens have already been validated. Construct the exact ordered JSON
 -- used by projectCapabilityAttention, without changing the retained input.
 canonical_metadata := '{"provider":' || (m->'provider')::text
   || ',"route":' || (m->'route')::text || ',"surface":' || (m->'surface')::text
   || ',"surfaceRevision":' || (m->'surfaceRevision')::text
   || ',"policyRevision":' || (m->'policyRevision')::text
   || ',"adapterRevision":' || (m->'adapterRevision')::text
   || ',"workerBuild":' || (m->'workerBuild')::text || '}';
 if c->>'scopeKey' is distinct from encode(sha256(convert_to(canonical_metadata, 'UTF8')), 'hex') then return false; end if;
 if e <> 'null'::jsonb then
   if not private.capability_preparation_integer(e->'observationRevision', 1, 9007199254740991)
     or not private.capability_preparation_time(e->'observedAt')
     or not private.capability_preparation_time(e->'expiresAt')
     or (e->>'observedAt')::timestamptz > (c->>'evaluatedAt')::timestamptz
     or (i->>'observedAt')::timestamptz is distinct from (e->>'observedAt')::timestamptz
     or (i->>'expiresAt')::timestamptz is distinct from (e->>'expiresAt')::timestamptz then return false; end if;
   if (e->>'expiresAt')::timestamptz <= (c->>'evaluatedAt')::timestamptz then
     if i->>'freshness' <> 'stale' or i->>'reasonCode' <> 'observation_stale'
       or i->>'severity' <> 'unknown' or i->'formatCounts' <> 'null'::jsonb then return false; end if;
   else
     if i->>'freshness' <> 'current' or i->>'reasonCode' <> e->'decision'->>'classification'
       or i->>'severity' <> (case when e->'decision'->>'classification' in ('matches_policy','reviewed_missing_accept_xometry') then 'healthy'
         when e->'decision'->>'classification' in ('format_added','format_removed') and jsonb_array_length(e->'decision'->'allowedExtensions') > 0 then 'attention' else 'blocked' end)
       or i->'formatCounts' is distinct from jsonb_build_object('allowed', jsonb_array_length(e->'decision'->'allowedExtensions'),
         'added', jsonb_array_length(e->'decision'->'reportedAddedExtensions'), 'removed', jsonb_array_length(e->'decision'->'reportedRemovedExtensions')) then return false; end if;
   end if;
 else
   if i->'observedAt' <> 'null'::jsonb or i->'expiresAt' <> 'null'::jsonb
     or i->>'freshness' <> 'unknown' or i->>'severity' <> 'unknown'
     or i->>'reasonCode' <> 'observation_missing' or i->'formatCounts' <> 'null'::jsonb then return false; end if;
 end if;
 if i->>'summary' <> (case i->>'severity'
   when 'healthy' then 'Upload capability matches the reviewed policy.'
   when 'attention' then 'Observed upload formats changed and require review.'
   when 'blocked' then 'Upload capability requires operator review.'
   else case when i->>'reasonCode' = 'observation_stale' then 'Upload capability evidence is stale.'
     else 'Upload capability evidence is missing or invalid.' end end) then return false; end if;
 if intent <> 'null'::jsonb and intent->>'kind' <> (case when i->>'severity' = 'healthy' then 'recovery' else 'attention' end) then return false; end if;
 return true;
exception when others then return false;
end $$;

create function private.capability_preparation_claim(p_input jsonb)
returns jsonb language plpgsql set search_path = pg_catalog as $$
declare prior jsonb; r jsonb := p_input->'request';
begin
  if not private.capability_preparation_json(p_input) or octet_length(p_input::text) > 16384
    or not private.capability_preparation_claim_valid(p_input) then raise exception using errcode = '22023', message = 'Invalid preparation.'; end if;
  perform pg_advisory_xact_lock(591, 1);
  select input into prior from private.capability_claim_preparations where request_key = (r->>'requestKey')::uuid;
  if found then
    if prior = p_input then return jsonb_build_object('state','existing','retained',prior); end if;
    raise exception using errcode = '23505', message = 'Preparation conflict.';
  end if;
  -- The UNIQUE completion key reserves it across every request and window.
  -- Window association itself is intentionally nonunique: the canonical claim
  -- remains the only owner/lease authority.
  insert into private.capability_claim_preparations(request_key, window_key, completion_key, cursor, input)
    values ((r->>'requestKey')::uuid, r->>'windowKey', (p_input->>'completionKey')::uuid,
      nextval('private.capability_preparation_cursor_seq'::regclass), p_input);
  return jsonb_build_object('state','created','retained',p_input);
end $$;
create function private.capability_preparation_completion(p_input jsonb)
returns jsonb language plpgsql set search_path = pg_catalog as $$
declare prior jsonb; retained jsonb; r jsonb; c jsonb := p_input->'candidate'; w private.capability_runtime_windows;
begin
  if not private.capability_preparation_json(p_input) or octet_length(p_input::text) > 16384
    or not private.capability_preparation_completion_valid(p_input) then raise exception using errcode = '22023', message = 'Invalid preparation.'; end if;
  perform pg_advisory_xact_lock(591, 1);
  select input into prior from private.capability_completion_preparations where completion_key = (p_input->>'completionKey')::uuid;
  if found then
    if prior = p_input then return jsonb_build_object('state','existing','retained',prior); end if;
    raise exception using errcode = '23505', message = 'Preparation conflict.';
  end if;
  -- Existing replay above survives changes to current state. A new preparation
  -- binds the retained identity to the actual canonical fence. No expiry check
  -- here can turn retention into authority to execute the completion.
  select input into retained from private.capability_claim_preparations where completion_key = (p_input->>'completionKey')::uuid;
  if not found then raise exception using errcode = '22023', message = 'Claim preparation required.'; end if;
  r := retained->'request';
  select * into w from private.capability_runtime_windows where window_key = p_input->>'windowKey';
  if not found or w.claim_input is distinct from r
    or r->'requestKey' is distinct from p_input->'requestKey'
    or r->'windowKey' is distinct from p_input->'windowKey'
    or w.fence::text is distinct from p_input->>'fence'
    or c->'provider' is distinct from r->'provider'
    or c->'route' is distinct from r->'route'
    or c->'surface' is distinct from r->'surface'
    or c->'revision' is distinct from r->'surfaceRevision'
    or (c->>'observedAt')::timestamptz < (r->>'windowStart')::timestamptz
    or (c->>'observedAt')::timestamptz >= (r->>'windowEnd')::timestamptz then
    raise exception using errcode = '22023', message = 'Preparation binding rejected.';
  end if;
  insert into private.capability_completion_preparations(completion_key,input) values ((p_input->>'completionKey')::uuid,p_input);
  return jsonb_build_object('state','created','retained',p_input);
end $$;
create function private.capability_preparation_attention(p_input jsonb)
returns jsonb language plpgsql set search_path = pg_catalog as $$
declare prior jsonb;
begin
  if not private.capability_preparation_json(p_input) or octet_length(p_input::text) > 16384
    or not private.capability_preparation_attention_valid(p_input) then raise exception using errcode = '22023', message = 'Invalid preparation.'; end if;
  perform pg_advisory_xact_lock(591, 1);
  select input into prior from private.capability_attention_preparations where evaluation_key = (p_input->>'evaluationKey')::uuid;
  if found then
    if prior = p_input then return jsonb_build_object('state','existing','retained',prior); end if;
    raise exception using errcode = '23505', message = 'Preparation conflict.';
  end if;
  insert into private.capability_attention_preparations(evaluation_key,scope_key,cursor,input)
    values ((p_input->>'evaluationKey')::uuid, p_input->'cursor'->>'scopeKey',
      nextval('private.capability_preparation_cursor_seq'::regclass), p_input);
  return jsonb_build_object('state','created','retained',p_input);
end $$;

-- A single static page validator is shared by the two typed discovery queries.
-- It returns the numeric lower bound, not a sequence allocation or dispatch token.
create function private.capability_preparation_after(p_after_cursor text, p_limit integer)
returns bigint language plpgsql immutable set search_path = pg_catalog as $$
begin
  if p_limit is null or p_limit not between 1 and 100 then raise exception using errcode = '22023', message = 'Invalid page.'; end if;
  if p_after_cursor is null then return 0; end if;
  if length(p_after_cursor) > 19 or p_after_cursor !~ '^[1-9][0-9]*$' then
    raise exception using errcode = '22023', message = 'Invalid cursor.';
  end if;
  if p_after_cursor::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Invalid cursor.';
  end if;
  return p_after_cursor::bigint;
end $$;

create function public.api_prepare_capability_claim(p_input jsonb)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
begin return private.capability_preparation_claim(p_input);
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability claim preparation rejected.'; end $$;
create function public.api_prepare_capability_completion(p_input jsonb)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
begin return private.capability_preparation_completion(p_input);
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability completion preparation rejected.'; end $$;
create function public.api_prepare_capability_attention(p_input jsonb)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
begin return private.capability_preparation_attention(p_input);
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability attention preparation rejected.'; end $$;
create function public.api_read_prepared_capability_claim(p_request_key text)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
declare result jsonb;
begin
  if not private.capability_preparation_uuid(to_jsonb(p_request_key)) then raise exception using errcode = '22023'; end if;
  select input into result from private.capability_claim_preparations where request_key = p_request_key::uuid;
  return result;
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability claim preparation read rejected.'; end $$;
create function public.api_read_prepared_capability_completion(p_completion_key text)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
declare result jsonb;
begin
  if not private.capability_preparation_uuid(to_jsonb(p_completion_key)) then raise exception using errcode = '22023'; end if;
  select input into result from private.capability_completion_preparations where completion_key = p_completion_key::uuid;
  return result;
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability completion preparation read rejected.'; end $$;
create function public.api_read_prepared_capability_attention(p_evaluation_key text)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
declare result jsonb;
begin
  if not private.capability_preparation_uuid(to_jsonb(p_evaluation_key)) then raise exception using errcode = '22023'; end if;
  select input into result from private.capability_attention_preparations where evaluation_key = p_evaluation_key::uuid;
  return result;
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability attention preparation read rejected.'; end $$;
create function public.api_list_prepared_capability_claims(p_window_key text, p_after_cursor text, p_limit integer)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
declare after_value bigint; rows jsonb; result jsonb; more boolean; last_cursor text;
begin
  if not private.capability_preparation_string(to_jsonb(p_window_key), '^canary:[a-f0-9]{64}$') then raise exception using errcode = '22023'; end if;
  after_value := private.capability_preparation_after(p_after_cursor, p_limit);
  with page as materialized (
    select cursor, input from private.capability_claim_preparations
    where window_key = p_window_key and cursor > after_value order by cursor limit p_limit + 1
  ), numbered as (select cursor, input, row_number() over (order by cursor) as n from page)
  select coalesce(jsonb_agg(jsonb_build_object('cursor',cursor::text,'input',input) order by cursor) filter (where n <= p_limit), '[]'::jsonb),
    count(*) > p_limit, (max(cursor) filter (where n <= p_limit))::text
  into rows, more, last_cursor from numbered;
  result := jsonb_build_object('entries',rows,'nextCursor',last_cursor,'hasMore',more);
  if octet_length(result::text) > 2000000 then raise exception using errcode = '22023'; end if;
  return result;
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability claim preparation listing rejected.'; end $$;
create function public.api_list_prepared_capability_attention(p_scope_key text, p_after_cursor text, p_limit integer)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $$
declare after_value bigint; rows jsonb; result jsonb; more boolean; last_cursor text;
begin
  if not private.capability_preparation_string(to_jsonb(p_scope_key), '^[a-f0-9]{64}$') then raise exception using errcode = '22023'; end if;
  after_value := private.capability_preparation_after(p_after_cursor, p_limit);
  with page as materialized (
    select cursor, input from private.capability_attention_preparations
    where scope_key = p_scope_key and cursor > after_value order by cursor limit p_limit + 1
  ), numbered as (select cursor, input, row_number() over (order by cursor) as n from page)
  select coalesce(jsonb_agg(jsonb_build_object('cursor',cursor::text,'input',input) order by cursor) filter (where n <= p_limit), '[]'::jsonb),
    count(*) > p_limit, (max(cursor) filter (where n <= p_limit))::text
  into rows, more, last_cursor from numbered;
  result := jsonb_build_object('entries',rows,'nextCursor',last_cursor,'hasMore',more);
  if octet_length(result::text) > 2000000 then raise exception using errcode = '22023'; end if;
  return result;
exception when others then raise exception using errcode = SQLSTATE, message = 'Capability attention preparation listing rejected.'; end $$;

-- Existing postgres executor pattern: no new role, membership, policy or auth setup.
alter table private.capability_claim_preparations owner to postgres;
alter table private.capability_claim_preparations enable row level security;
alter table private.capability_claim_preparations force row level security;
revoke all on table private.capability_claim_preparations from public, anon, authenticated, service_role;
alter table private.capability_completion_preparations owner to postgres;
alter table private.capability_completion_preparations enable row level security;
alter table private.capability_completion_preparations force row level security;
revoke all on table private.capability_completion_preparations from public, anon, authenticated, service_role;
alter table private.capability_attention_preparations owner to postgres;
alter table private.capability_attention_preparations enable row level security;
alter table private.capability_attention_preparations force row level security;
revoke all on table private.capability_attention_preparations from public, anon, authenticated, service_role;
alter sequence private.capability_preparation_cursor_seq owner to postgres;
revoke all on sequence private.capability_preparation_cursor_seq from public, anon, authenticated, service_role;
alter function private.capability_preparation_json(jsonb,integer) owner to postgres;
revoke all on function private.capability_preparation_json(jsonb,integer) from public, anon, authenticated, service_role;
alter function private.capability_preparation_string(jsonb,text) owner to postgres;
revoke all on function private.capability_preparation_string(jsonb,text) from public, anon, authenticated, service_role;
alter function private.capability_preparation_uuid(jsonb) owner to postgres;
revoke all on function private.capability_preparation_uuid(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_integer(jsonb,bigint,bigint) owner to postgres;
revoke all on function private.capability_preparation_integer(jsonb,bigint,bigint) from public, anon, authenticated, service_role;
alter function private.capability_preparation_time(jsonb) owner to postgres;
revoke all on function private.capability_preparation_time(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_tokens(jsonb,text) owner to postgres;
revoke all on function private.capability_preparation_tokens(jsonb,text) from public, anon, authenticated, service_role;
alter function private.capability_preparation_claim_valid(jsonb) owner to postgres;
revoke all on function private.capability_preparation_claim_valid(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_completion_valid(jsonb) owner to postgres;
revoke all on function private.capability_preparation_completion_valid(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_attention_valid(jsonb) owner to postgres;
revoke all on function private.capability_preparation_attention_valid(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_claim(jsonb) owner to postgres;
revoke all on function private.capability_preparation_claim(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_completion(jsonb) owner to postgres;
revoke all on function private.capability_preparation_completion(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_attention(jsonb) owner to postgres;
revoke all on function private.capability_preparation_attention(jsonb) from public, anon, authenticated, service_role;
alter function private.capability_preparation_after(text,integer) owner to postgres;
revoke all on function private.capability_preparation_after(text,integer) from public, anon, authenticated, service_role;
alter function public.api_prepare_capability_claim(jsonb) owner to postgres;
revoke all on function public.api_prepare_capability_claim(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.api_prepare_capability_claim(jsonb) to service_role;
alter function public.api_prepare_capability_completion(jsonb) owner to postgres;
revoke all on function public.api_prepare_capability_completion(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.api_prepare_capability_completion(jsonb) to service_role;
alter function public.api_prepare_capability_attention(jsonb) owner to postgres;
revoke all on function public.api_prepare_capability_attention(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.api_prepare_capability_attention(jsonb) to service_role;
alter function public.api_read_prepared_capability_claim(text) owner to postgres;
revoke all on function public.api_read_prepared_capability_claim(text) from public, anon, authenticated, service_role;
grant execute on function public.api_read_prepared_capability_claim(text) to service_role;
alter function public.api_read_prepared_capability_completion(text) owner to postgres;
revoke all on function public.api_read_prepared_capability_completion(text) from public, anon, authenticated, service_role;
grant execute on function public.api_read_prepared_capability_completion(text) to service_role;
alter function public.api_read_prepared_capability_attention(text) owner to postgres;
revoke all on function public.api_read_prepared_capability_attention(text) from public, anon, authenticated, service_role;
grant execute on function public.api_read_prepared_capability_attention(text) to service_role;
alter function public.api_list_prepared_capability_claims(text,text,integer) owner to postgres;
revoke all on function public.api_list_prepared_capability_claims(text,text,integer) from public, anon, authenticated, service_role;
grant execute on function public.api_list_prepared_capability_claims(text,text,integer) to service_role;
alter function public.api_list_prepared_capability_attention(text,text,integer) owner to postgres;
revoke all on function public.api_list_prepared_capability_attention(text,text,integer) from public, anon, authenticated, service_role;
grant execute on function public.api_list_prepared_capability_attention(text,text,integer) to service_role;
commit;
