-- OVD-591 additive persistence. Filename generated by authorized Mac owner with Supabase CLI 2.78.1.
-- No database execution is claimed. Operational disable: revoke new RPCs, retain history.
begin;
create table private.capability_runtime_revisions (
 scope_key text primary key, high_water bigint not null check(high_water between 1 and 9007199254740991)
);
create function private.capability_runtime_scope(p_provider text,p_route text,p_surface text,p_revision text)
returns text language sql immutable set search_path=pg_catalog as $$
 select p_provider||':'||'provider_upload'||':'||lower(btrim(p_route))||':'||lower(btrim(p_surface))||':'||lower(btrim(p_revision))
$$;

create or replace function private.record_capability_observation(
  p_provider public.vendor_name,
  p_capability text,
  p_route text,
  p_surface text,
  p_surface_revision text,
  p_contract_version text,
  p_observation_state text,
  p_observed_extensions text[],
  p_observed_mime_types text[],
  p_accept_attribute_present boolean,
  p_observed_at timestamptz,
  p_expires_at timestamptz,
  p_actor_kind text,
  p_source_kind text,
  p_source_version text,
  p_evidence_reference text,
  p_idempotency_key text,
  p_observation_revision bigint
)
returns bigint
language plpgsql
set search_path = pg_catalog
as $$
declare
  v_capability text := pg_catalog.lower(pg_catalog.btrim(p_capability));
  v_route text := pg_catalog.lower(pg_catalog.btrim(p_route));
  v_surface text := pg_catalog.lower(pg_catalog.btrim(p_surface));
  v_surface_revision text := pg_catalog.lower(pg_catalog.btrim(p_surface_revision));
  v_contract_version text := pg_catalog.lower(pg_catalog.btrim(p_contract_version));
  v_observation_state text := pg_catalog.lower(pg_catalog.btrim(p_observation_state));
  v_observed_extensions text[];
  v_observed_mime_types text[];
  v_actor_kind text := pg_catalog.lower(pg_catalog.btrim(p_actor_kind));
  v_source_kind text := pg_catalog.lower(pg_catalog.btrim(p_source_kind));
  v_source_version text := pg_catalog.lower(pg_catalog.btrim(p_source_version));
  v_evidence_reference text := pg_catalog.btrim(p_evidence_reference);
  v_idempotency_key text := pg_catalog.lower(pg_catalog.btrim(p_idempotency_key));
  v_idempotency_lock bigint;
  v_revision_lock bigint;
  v_existing_count integer;
  v_exact_id bigint;
  v_inserted_id bigint;
begin
  -- Shared serialization precedes every existing replay lock. No signature change.
  perform pg_catalog.pg_advisory_xact_lock(591, 1);
  if p_observation_revision > 9007199254740991 then
    raise exception using errcode = '22023', message = 'Capability revision exhausted.';
  end if;
  select coalesce(
    pg_catalog.array_agg(normalized_extension order by normalized_extension),
    array[]::text[]
  )
  into v_observed_extensions
  from (
    select distinct pg_catalog.regexp_replace(
      pg_catalog.lower(pg_catalog.btrim(extension_value)),
      '^[.]',
      ''
    ) as normalized_extension
    from pg_catalog.unnest(
      coalesce(p_observed_extensions, array[]::text[])
    ) as extension_value
  ) normalized_extensions;

  select coalesce(
    pg_catalog.array_agg(normalized_mime_type order by normalized_mime_type),
    array[]::text[]
  )
  into v_observed_mime_types
  from (
    select distinct pg_catalog.lower(
      pg_catalog.btrim(mime_type_value)
    ) as normalized_mime_type
    from pg_catalog.unnest(
      coalesce(p_observed_mime_types, array[]::text[])
    ) as mime_type_value
  ) normalized_mime_types;

  v_idempotency_lock := pg_catalog.hashtextextended(
    'capability-observation:idempotency:' || v_idempotency_key,
    0
  );
  v_revision_lock := pg_catalog.hashtextextended(
    'capability-observation:revision:'
      || p_provider::text || ':'
      || v_capability || ':'
      || v_route || ':'
      || v_surface || ':'
      || v_surface_revision || ':'
      || p_observation_revision::text,
    0
  );

  perform pg_catalog.pg_advisory_xact_lock(
    least(v_idempotency_lock, v_revision_lock)
  );
  if v_idempotency_lock <> v_revision_lock then
    perform pg_catalog.pg_advisory_xact_lock(
      greatest(v_idempotency_lock, v_revision_lock)
    );
  end if;

  select
    pg_catalog.count(*)::integer,
    pg_catalog.min(observation.id) filter (
      where observation.idempotency_key = v_idempotency_key
        and observation.provider = p_provider
        and observation.capability = v_capability
        and observation.route = v_route
        and observation.surface = v_surface
        and observation.surface_revision = v_surface_revision
        and observation.observation_revision = p_observation_revision
        and observation.contract_version is not distinct from v_contract_version
        and observation.observation_state is not distinct from v_observation_state
        and observation.observed_extensions is not distinct from v_observed_extensions
        and observation.observed_mime_types is not distinct from v_observed_mime_types
        and observation.accept_attribute_present is not distinct from p_accept_attribute_present
        and observation.observed_at is not distinct from p_observed_at
        and observation.expires_at is not distinct from p_expires_at
        and observation.actor_kind is not distinct from v_actor_kind
        and observation.source_kind is not distinct from v_source_kind
        and observation.source_version is not distinct from v_source_version
        and observation.evidence_reference is not distinct from v_evidence_reference
    )
  into v_existing_count, v_exact_id
  from private.capability_observations observation
  where observation.idempotency_key = v_idempotency_key
    or (
      observation.provider = p_provider
      and observation.capability = v_capability
      and observation.route = v_route
      and observation.surface = v_surface
      and observation.surface_revision = v_surface_revision
      and observation.observation_revision = p_observation_revision
    );

  if v_existing_count > 0 then
    if v_existing_count = 1 and v_exact_id is not null then
      return v_exact_id;
    end if;

    raise exception using
      errcode = '23505',
      message = 'Capability observation replay conflict.';
  end if;

  if exists(select from private.capability_runtime_windows w where not w.completed and w.scope_key=private.capability_runtime_scope(p_provider::text,v_route,v_surface,v_surface_revision) and w.observation_revision=p_observation_revision) then
    raise exception 'Revision reserved';
  end if;
  insert into private.capability_observations (
    provider,
    capability,
    route,
    surface,
    surface_revision,
    contract_version,
    observation_state,
    observed_extensions,
    observed_mime_types,
    accept_attribute_present,
    observed_at,
    expires_at,
    actor_kind,
    source_kind,
    source_version,
    evidence_reference,
    idempotency_key,
    observation_revision
  ) values (
    p_provider,
    v_capability,
    v_route,
    v_surface,
    v_surface_revision,
    v_contract_version,
    v_observation_state,
    v_observed_extensions,
    v_observed_mime_types,
    p_accept_attribute_present,
    p_observed_at,
    p_expires_at,
    v_actor_kind,
    v_source_kind,
    v_source_version,
    v_evidence_reference,
    v_idempotency_key,
    p_observation_revision
  )
  returning id into v_inserted_id;

  insert into private.capability_runtime_revisions(scope_key,high_water)
  values(private.capability_runtime_scope(p_provider::text,v_route,v_surface,v_surface_revision),p_observation_revision)
  on conflict(scope_key) do update set high_water=greatest(private.capability_runtime_revisions.high_water,excluded.high_water);
  return v_inserted_id;
end;
$$;

create table private.capability_runtime_windows (
 window_key text primary key, claim_input jsonb not null, fence uuid not null,
 window_start timestamptz not null, scope_key text not null, unique(scope_key,window_start), deadline timestamptz not null, observation_revision bigint not null, resource_key text not null, completed boolean not null default false, completion_input jsonb, receipt jsonb
);
create table private.capability_attention_state (
 scope_key text primary key, version bigint not null check(version between 1 and 9007199254740991),
 cursor jsonb not null, item jsonb not null, evidence jsonb, due_at timestamptz
);
create table private.capability_attention_outbox (
 intent_key text primary key, scope_key text not null references private.capability_attention_state,
 intent jsonb not null
);
create table private.capability_attention_evaluations (
 evaluation_key text primary key, input jsonb not null, receipt jsonb not null
);
-- Only owner functions can access these private, forced-RLS relations.
create function private.capability_runtime_keys(p jsonb, keys text[]) returns boolean
language sql immutable set search_path=pg_catalog as $$
 select coalesce(jsonb_typeof(p)='object' and p ?& keys and (select count(*) from jsonb_object_keys(p))=cardinality(keys),false)
$$;
create function private.capability_runtime_claim(p_input jsonb) returns jsonb
language plpgsql set search_path=pg_catalog as $$
declare w private.capability_runtime_windows; t timestamptz; rev bigint; scope text; receipt jsonb;
begin
 if not private.capability_runtime_keys(p_input,array['windowKey','resourceKey','configDigest','requestKey','provider','route','surface','surfaceRevision','windowStart','windowEnd','leaseSeconds'])
 or octet_length(p_input::text)>4096 then raise exception 'Invalid claim'; end if;
 if (p_input->>'windowKey') !~ '^canary:[a-f0-9]{64}$' or (p_input->>'resourceKey') !~ '^[a-f0-9]{64}$' or (p_input->>'configDigest') !~ '^[a-f0-9]{64}$'
 or exists(select from jsonb_each_text(p_input) x where x.key in ('provider','route','surface','surfaceRevision') and x.value !~ '^[a-z][a-z0-9._-]{0,79}$')
 or (p_input->>'leaseSeconds') !~ '^[0-9]{1,3}$' or (p_input->>'leaseSeconds')::int not between 1 and 300
 or p_input->>'requestKey' is null then raise exception 'Invalid claim'; end if;
 if exists(select from jsonb_each(p_input) x where x.value='null'::jsonb) then raise exception 'Null claim'; end if;
 if p_input->>'requestKey' is distinct from ((p_input->>'requestKey')::uuid)::text then raise exception 'Invalid owner'; end if;
 perform (p_input->>'provider')::public.vendor_name;
 perform pg_advisory_xact_lock(591,1);
 t:=clock_timestamp();
 select * into w from private.capability_runtime_windows where window_key=p_input->>'windowKey';
 if found then
   if w.claim_input - 'requestKey' <> p_input - 'requestKey' then raise exception 'Claim conflict'; end if;
   if w.claim_input->>'requestKey' <> p_input->>'requestKey' then return jsonb_build_object('status','busy'); end if;
   return jsonb_build_object('status',case when w.completed then 'completed' when w.deadline<=t then 'expired' else 'replay' end,'windowKey',w.window_key,'fence',w.fence,'generation',1,'owner',w.claim_input->>'requestKey','observationRevision',w.observation_revision,'deadline',w.deadline);
 end if;
 if (p_input->>'windowStart')::timestamptz > t or (p_input->>'windowEnd')::timestamptz<=t
 or (p_input->>'windowEnd')::timestamptz <= (p_input->>'windowStart')::timestamptz
 or (p_input->>'windowEnd')::timestamptz-(p_input->>'windowStart')::timestamptz > interval '26 hours' then raise exception 'Invalid window'; end if;
 if exists(select from private.capability_runtime_windows where resource_key=p_input->>'resourceKey' and not completed) then return jsonb_build_object('status','busy'); end if;
 scope:=private.capability_runtime_scope(p_input->>'provider',p_input->>'route',p_input->>'surface',p_input->>'surfaceRevision');
 select greatest(coalesce((select high_water from private.capability_runtime_revisions where scope_key=scope),0),coalesce(max(observation_revision),0))+1 into rev
 from private.capability_observations where provider::text=p_input->>'provider' and capability='provider_upload' and route=p_input->>'route' and surface=p_input->>'surface' and surface_revision=p_input->>'surfaceRevision';
 if rev>9007199254740991 then raise exception 'Revision exhausted'; end if;
 insert into private.capability_runtime_revisions values(scope,rev) on conflict(scope_key) do update set high_water=excluded.high_water;
 insert into private.capability_runtime_windows(window_key,claim_input,fence,window_start,scope_key,deadline,observation_revision,resource_key)
 values(p_input->>'windowKey',p_input,gen_random_uuid(),(p_input->>'windowStart')::timestamptz,scope,least((p_input->>'windowEnd')::timestamptz,t+make_interval(secs=>(p_input->>'leaseSeconds')::int)),rev,p_input->>'resourceKey') returning * into w;
 return jsonb_build_object('status','claimed','windowKey',w.window_key,'fence',w.fence,'generation',1,'owner',w.claim_input->>'requestKey','observationRevision',rev,'deadline',w.deadline);
end $$;
create function private.capability_runtime_complete(p_input jsonb) returns jsonb
language plpgsql set search_path=pg_catalog as $$
declare w private.capability_runtime_windows; c jsonb; r jsonb;
begin
 if not private.capability_runtime_keys(p_input,array['windowKey','requestKey','fence','completionKey','candidate','resourceReleased']) or octet_length(p_input::text)>16384 then raise exception 'Invalid completion'; end if;
 if p_input->'resourceReleased' is distinct from 'true'::jsonb then raise exception 'Resource disposal required'; end if;
 if exists(select from jsonb_each(p_input) x where x.value='null'::jsonb) then raise exception 'Null completion'; end if;
 perform (p_input->>'completionKey')::uuid;
 perform pg_advisory_xact_lock(591,1);
 select * into w from private.capability_runtime_windows where window_key=p_input->>'windowKey';
 if not found or w.claim_input->>'requestKey'<>p_input->>'requestKey' or w.fence::text<>p_input->>'fence' then raise exception 'Fence rejected'; end if;
 if w.completed then
  if w.completion_input=p_input then return w.receipt; end if;
  raise exception 'Completion conflict';
 end if;
 if w.deadline<=clock_timestamp() then raise exception 'Fence expired'; end if;
 c:=p_input->'candidate';
 if not private.capability_runtime_keys(c,array['provider','route','surface','revision','state','extensions','mimeTypes','acceptAttributePresent','observedAt','expiresAt','actorKind','sourceKind','sourceVersion','evidenceReference','idempotencyKey'])
 or c->>'provider'<>w.claim_input->>'provider' or c->>'route'<>w.claim_input->>'route' or c->>'surface'<>w.claim_input->>'surface' or c->>'revision'<>w.claim_input->>'surfaceRevision'
 or c->>'idempotencyKey'<>w.window_key or c->>'actorKind'<>'scheduled_canary' or c->>'sourceKind'<>'scheduled_canary' then raise exception 'Candidate rejected'; end if;
 if exists(select from private.capability_observations where provider::text=c->>'provider' and capability='provider_upload' and route=c->>'route' and surface=c->>'surface' and surface_revision=c->>'revision' and (observation_revision>=w.observation_revision or observed_at>(c->>'observedAt')::timestamptz)) then raise exception 'Reservation superseded'; end if;
 if exists(select from jsonb_each(c) x where x.value='null'::jsonb and x.key<>'acceptAttributePresent') then raise exception 'Null candidate'; end if;
 if (c->>'observedAt')::timestamptz>clock_timestamp() or (c->>'expiresAt')::timestamptz<=clock_timestamp() or (c->>'expiresAt')::timestamptz-(c->>'observedAt')::timestamptz>interval '1 hour' then raise exception 'Invalid capture freshness'; end if;
 if (c->>'observedAt')::timestamptz < (w.claim_input->>'windowStart')::timestamptz or (c->>'observedAt')::timestamptz >= (w.claim_input->>'windowEnd')::timestamptz then raise exception 'Observation outside window'; end if;
 update private.capability_runtime_windows set completed=true where window_key=w.window_key;
 perform private.record_capability_observation((c->>'provider')::public.vendor_name,'provider_upload',c->>'route',c->>'surface',c->>'revision','provider-upload-capability.v1',c->>'state',array(select jsonb_array_elements_text(c->'extensions')),array(select jsonb_array_elements_text(c->'mimeTypes')),(c->>'acceptAttributePresent')::boolean,(c->>'observedAt')::timestamptz,(c->>'expiresAt')::timestamptz,c->>'actorKind',c->>'sourceKind',c->>'sourceVersion',c->>'evidenceReference',c->>'idempotencyKey',w.observation_revision);
 r:=jsonb_build_object('status','completed','windowKey',w.window_key,'observationRevision',w.observation_revision);
 update private.capability_runtime_windows set completed=true,completion_input=p_input,receipt=r where window_key=w.window_key;
 return r;
end $$;
create function private.capability_runtime_attention(p jsonb) returns jsonb
language plpgsql set search_path=pg_catalog as $$
declare old private.capability_attention_state; replay private.capability_attention_evaluations;
 c jsonb:=p->'cursor'; i jsonb:=p->'item'; intent jsonb:=p->'intent'; e jsonb:=p->'evidence'; m jsonb;
 v bigint; head bigint; head_time timestamptz; head_expiry timestamptz; receipt jsonb; k text;
begin
 if not private.capability_runtime_keys(p,array['expectedVersion','evaluationKey','cursor','item','intent','evidence']) or octet_length(p::text)>16384 then raise exception 'Invalid attention'; end if;
 if jsonb_typeof(p->'expectedVersion') is distinct from 'number' or jsonb_typeof(p->'evaluationKey') is distinct from 'string' then raise exception 'Invalid CAS'; end if;
 perform (p->>'evaluationKey')::uuid;
 if not private.capability_runtime_keys(c,array['scopeKey','fingerprint','generation','lastObservationRevision','lastObservedAt','lastEvidenceHash','evaluatedAt'])
 or not private.capability_runtime_keys(i,array['key','category','metadata','severity','reasonCode','summary','freshness','observedAt','expiresAt','checkedAt','formatCounts','occurrenceCount','firstSeenAt','lastChangedAt','action'])
 then raise exception 'Invalid projection'; end if;
 if exists(select from jsonb_each(c) x where x.value='null'::jsonb and x.key not in ('lastObservationRevision','lastObservedAt','lastEvidenceHash'))
 or exists(select from jsonb_each(i) x where x.value='null'::jsonb and x.key not in ('observedAt','expiresAt','formatCounts','occurrenceCount','firstSeenAt','lastChangedAt','action'))
 or jsonb_typeof(c->'generation') is distinct from 'number'
 or jsonb_typeof(c->'lastObservationRevision') not in ('number','null')
 or jsonb_typeof(c->'lastObservedAt') not in ('string','null') or jsonb_typeof(c->'lastEvidenceHash') not in ('string','null')
 or (c->'lastObservationRevision'<>'null'::jsonb and ((c->>'lastObservationRevision')::bigint not between 1 and 9007199254740991 or c->>'lastEvidenceHash' !~ '^[a-f0-9]{64}$' or c->'lastObservedAt'='null'::jsonb or c->'lastEvidenceHash'='null'::jsonb))
 or (c->'lastObservationRevision'='null'::jsonb and (c->'lastObservedAt'<>'null'::jsonb or c->'lastEvidenceHash'<>'null'::jsonb)) then raise exception 'Invalid cursor'; end if;
 if exists(select from jsonb_each(c) x where (x.key='generation' and jsonb_typeof(x.value)<>'number') or (x.key not in ('generation','lastObservationRevision','lastObservedAt','lastEvidenceHash') and jsonb_typeof(x.value)<>'string')) then raise exception 'Invalid cursor types'; end if;
 m:=i->'metadata';
 if not private.capability_runtime_keys(m,array['provider','route','surface','surfaceRevision','policyRevision','adapterRevision','workerBuild'])
 or exists(select from jsonb_each(m) x where jsonb_typeof(x.value) not in ('string','null'))
 or exists(select from jsonb_each_text(m) x where (x.value is null and x.key not in ('adapterRevision','workerBuild')) or (x.value is not null and x.value !~ '^[a-z][a-z0-9._-]{0,79}$'))
 or c->>'scopeKey' !~ '^[a-f0-9]{64}$' or c->>'fingerprint' !~ '^[a-f0-9]{64}$'
 or i->>'key' <> 'capability:'||(c->>'scopeKey') or i->>'category'<>'provider_upload_capability'
 or i->>'severity' not in ('healthy','attention','blocked','unknown') or i->>'freshness' not in ('current','stale','unknown')
 or i->'action'<>'null'::jsonb or i->'occurrenceCount'<>'null'::jsonb or i->'firstSeenAt'<>'null'::jsonb or i->'lastChangedAt'<>'null'::jsonb
 or i->>'summary' not in ('Upload capability matches the reviewed policy.','Observed upload formats changed and require review.','Upload capability requires operator review.','Upload capability evidence is stale.','Upload capability evidence is missing or invalid.')
 or i->>'reasonCode' not in ('matches_policy','format_added','format_removed','reviewed_missing_accept_xometry','accept_missing','unsupported','denied','observation_missing','observation_stale','formats_loading','ambiguous_input','route_or_selector_drift','authentication_required','anti_bot_or_challenge','provider_error','unclassified_response','source_malformed')
 or (c->>'generation')::bigint not between 0 and 1000000 or (p->>'expectedVersion')::bigint not between 0 and 9007199254740990
 or i->>'checkedAt'<>c->>'evaluatedAt' then raise exception 'Invalid projection'; end if;
 if i->'formatCounts'<>'null'::jsonb and exists(select from jsonb_each(i->'formatCounts') x where jsonb_typeof(x.value)<>'number') then raise exception 'Invalid count types'; end if;
 if i->'formatCounts'<>'null'::jsonb and (not private.capability_runtime_keys(i->'formatCounts',array['allowed','added','removed']) or exists(select from jsonb_each_text(i->'formatCounts') x where x.value !~ '^[0-9]{1,2}$' or x.value::int>32)) then raise exception 'Invalid counts'; end if;
 if e<>'null'::jsonb then
 if jsonb_typeof(e->'observationRevision') is distinct from 'number' or exists(select from jsonb_each(e) x where x.value='null'::jsonb) then raise exception 'Null evidence'; end if;
 if not private.capability_runtime_keys(e,array['decision','observedAt','expiresAt','observationRevision'])
 or not private.capability_runtime_keys(e->'decision',array['contractVersion','classification','allowedExtensions','reportedAddedExtensions','reportedRemovedExtensions','evidenceRefs','normalizedObservedMimeTypes'])
 or e->'decision'->>'contractVersion'<>'provider-upload-capability.v1'
 or e->'decision'->>'classification' not in ('matches_policy','format_added','format_removed','reviewed_missing_accept_xometry','accept_missing','unsupported','denied','observation_missing','observation_stale','formats_loading','ambiguous_input','route_or_selector_drift','authentication_required','anti_bot_or_challenge','provider_error','unclassified_response')
 or (e->>'observationRevision')::bigint is distinct from (c->>'lastObservationRevision')::bigint
 or (e->>'observedAt')::timestamptz is distinct from (c->>'lastObservedAt')::timestamptz
 or (e->>'expiresAt')::timestamptz <= (e->>'observedAt')::timestamptz
 or (e->>'expiresAt')::timestamptz-(e->>'observedAt')::timestamptz>interval '26 hours'
 then raise exception 'Invalid evidence'; end if;
 if exists(select from jsonb_each(e->'decision') x where x.value='null'::jsonb) then raise exception 'Null decision'; end if;
 foreach k in array array['allowedExtensions','reportedAddedExtensions','reportedRemovedExtensions','evidenceRefs','normalizedObservedMimeTypes'] loop
  if jsonb_typeof(e->'decision'->k)<>'array' or exists(select from jsonb_array_elements(e->'decision'->k) x where jsonb_typeof(x)<>'string') or jsonb_array_length(e->'decision'->k)>32 or exists(select from jsonb_array_elements_text(e->'decision'->k) x where x !~ case when k='evidenceRefs' then '^issue:OVD-[1-9][0-9]{0,9}$' when k='normalizedObservedMimeTypes' then '^[a-z0-9][a-z0-9!#$&^_.+-]{0,126}/[a-z0-9][a-z0-9!#$&^_.+-]{0,126}$' else '^[a-z0-9][a-z0-9_-]{0,31}$' end) then raise exception 'Invalid evidence tokens'; end if;
 end loop;
 end if;
 if intent<>'null'::jsonb and exists(select from jsonb_each(intent) x where x.value='null'::jsonb or (x.key='generation' and jsonb_typeof(x.value)<>'number') or (x.key<>'generation' and jsonb_typeof(x.value)<>'string')) then raise exception 'Invalid intent types'; end if;
 if intent<>'null'::jsonb and (not private.capability_runtime_keys(intent,array['key','itemKey','generation','kind','reasonCode']) or intent->>'key' !~ '^[a-f0-9]{64}$' or intent->>'itemKey'<>i->>'key' or intent->>'generation'<>c->>'generation' or intent->>'kind' not in ('attention','recovery') or intent->>'reasonCode'<>i->>'reasonCode') then raise exception 'Invalid intent'; end if;
 perform pg_advisory_xact_lock(591,1);
 select * into replay from private.capability_attention_evaluations where evaluation_key=p->>'evaluationKey';
 if found then
  if replay.input=p then return replay.receipt; end if;
  raise exception 'Evaluation conflict';
 end if;
 if (c->>'evaluatedAt')::timestamptz>clock_timestamp() then raise exception 'Future evaluation'; end if;
 select observation_revision,observed_at,expires_at into head,head_time,head_expiry from private.capability_observations where provider::text=m->>'provider' and capability='provider_upload' and route=m->>'route' and surface=m->>'surface' and surface_revision=m->>'surfaceRevision' order by observed_at desc,observation_revision desc limit 1;
 if head is distinct from (c->>'lastObservationRevision')::bigint or head_time is distinct from (c->>'lastObservedAt')::timestamptz then raise exception 'Evidence superseded'; end if;
 if head is null and (i->'observedAt'<>'null'::jsonb or i->'expiresAt'<>'null'::jsonb or i->>'freshness'<>'unknown' or i->>'severity'<>'unknown' or i->>'reasonCode'<>'observation_missing' or i->'formatCounts'<>'null'::jsonb) then raise exception 'Missing evidence times'; end if;
 if e='null'::jsonb and head is not null then raise exception 'Evidence required'; end if;
 if head_expiry>(c->>'evaluatedAt')::timestamptz and (i->>'freshness'<>'current' or i->>'reasonCode'<>e->'decision'->>'classification'
 or i->>'severity'<>case when e->'decision'->>'classification' in ('matches_policy','reviewed_missing_accept_xometry') then 'healthy' when e->'decision'->>'classification' in ('format_added','format_removed') and jsonb_array_length(e->'decision'->'allowedExtensions')>0 then 'attention' else 'blocked' end
 or i->'formatCounts' is distinct from jsonb_build_object('allowed',jsonb_array_length(e->'decision'->'allowedExtensions'),'added',jsonb_array_length(e->'decision'->'reportedAddedExtensions'),'removed',jsonb_array_length(e->'decision'->'reportedRemovedExtensions'))) then raise exception 'Projection mismatch'; end if;
 if head_expiry<=(c->>'evaluatedAt')::timestamptz and (i->>'freshness'<>'stale' or i->>'reasonCode'<>'observation_stale' or i->>'severity'<>'unknown' or i->'formatCounts'<>'null'::jsonb) then raise exception 'Stale evidence'; end if;
 if e<>'null'::jsonb and ((e->>'expiresAt')::timestamptz is distinct from head_expiry or (i->>'expiresAt')::timestamptz is distinct from head_expiry or (i->>'observedAt')::timestamptz is distinct from head_time) then raise exception 'Evidence time mismatch'; end if;
 if exists(select from private.capability_attention_state where item->'metadata'=m and scope_key<>c->>'scopeKey') then raise exception 'Scope identity conflict'; end if;
 select * into old from private.capability_attention_state where scope_key=c->>'scopeKey';
 if coalesce(old.version,0)<>(p->>'expectedVersion')::bigint then return jsonb_build_object('status','conflict'); end if;
 if old.version is not null and (old.item->'metadata'<>m or (c->>'evaluatedAt')::timestamptz<(old.cursor->>'evaluatedAt')::timestamptz
 or (c->>'lastObservationRevision')::bigint<(old.cursor->>'lastObservationRevision')::bigint
 or (c->>'lastObservedAt')::timestamptz<(old.cursor->>'lastObservedAt')::timestamptz
 or ((c->>'lastObservationRevision')::bigint=(old.cursor->>'lastObservationRevision')::bigint and (c->'lastEvidenceHash'<>old.cursor->'lastEvidenceHash' or e<>old.evidence))
 or (c->>'generation')::bigint<(old.cursor->>'generation')::bigint or (c->>'generation')::bigint>(old.cursor->>'generation')::bigint+1) then raise exception 'Cursor regression'; end if;
 if (c->>'generation')::bigint<>coalesce((old.cursor->>'generation')::bigint,0)+(case when intent='null'::jsonb then 0 else 1 end) then raise exception 'Generation mismatch'; end if;
 if old.version is not null and ((c->>'fingerprint'=old.cursor->>'fingerprint' and (intent<>'null'::jsonb or c->'generation'<>old.cursor->'generation')) or (c->>'fingerprint'<>old.cursor->>'fingerprint' and intent='null'::jsonb)) then raise exception 'Invalid transition'; end if;
 if old.version is null and ((i->>'severity'='healthy' and intent<>'null'::jsonb) or (i->>'severity'<>'healthy' and intent='null'::jsonb)) then raise exception 'Invalid initial transition'; end if;
 if intent<>'null'::jsonb and intent->>'kind'<>(case when i->>'severity'='healthy' then 'recovery' else 'attention' end) then raise exception 'Invalid intent kind'; end if;
 v:=coalesce(old.version,0)+1;
 insert into private.capability_attention_state values(c->>'scopeKey',v,c,i,e,case when i->>'freshness'='current' then (i->>'expiresAt')::timestamptz else null end)
 on conflict(scope_key) do update set version=excluded.version,cursor=excluded.cursor,item=excluded.item,evidence=excluded.evidence,due_at=excluded.due_at;
 if intent<>'null'::jsonb then insert into private.capability_attention_outbox values(intent->>'key',c->>'scopeKey',intent); end if;
 receipt:=jsonb_build_object('status','committed','version',v);
 insert into private.capability_attention_evaluations values(p->>'evaluationKey',p,receipt);
 return receipt;
end $$;
create function public.api_claim_capability_window(p_input jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog as $$ begin return private.capability_runtime_claim(p_input); exception when others then raise exception using errcode=SQLSTATE,message='Capability claim rejected.'; end $$;
create function public.api_complete_capability_window(p_input jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog as $$ begin return private.capability_runtime_complete(p_input); exception when others then raise exception using errcode=SQLSTATE,message='Capability completion rejected.'; end $$;
create function public.api_commit_capability_attention(p_input jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog as $$ begin return private.capability_runtime_attention(p_input); exception when others then raise exception using errcode=SQLSTATE,message='Capability attention rejected.'; end $$;
create function public.api_get_capability_window(p_window_key text,p_request_key uuid) returns jsonb language sql security definer set search_path=pg_catalog as $$
 select coalesce((select jsonb_build_object('status',case when completed then 'completed' when deadline<=clock_timestamp() then 'expired' else 'replay' end,'windowKey',window_key,'fence',fence,'generation',1,'owner',claim_input->>'requestKey','observationRevision',observation_revision,'deadline',deadline) from private.capability_runtime_windows where window_key=p_window_key and claim_input->>'requestKey'=p_request_key::text),' {"status":"unknown"}'::jsonb)
$$;
create function public.api_read_capability_attention(p_scope_key text) returns jsonb language sql security definer set search_path=pg_catalog as $$
 select jsonb_build_object('version',version,'cursor',cursor,'item',item,'evidence',evidence) from private.capability_attention_state where scope_key=p_scope_key
$$;
create function public.api_list_due_capability_attention(p_limit integer) returns jsonb language sql security definer set search_path=pg_catalog as $$
 select coalesce(jsonb_agg(row),'[]'::jsonb) from (select jsonb_build_object('version',version,'cursor',cursor,'item',item,'evidence',evidence) as row from private.capability_attention_state where due_at<=clock_timestamp() order by due_at,scope_key limit greatest(0,least(coalesce(p_limit,0),100))) s
$$;
alter table private.capability_runtime_revisions owner to postgres;
alter table private.capability_runtime_revisions enable row level security;
alter table private.capability_runtime_revisions force row level security;
revoke all on private.capability_runtime_revisions from public, anon, authenticated, service_role;
alter table private.capability_runtime_windows owner to postgres;
alter table private.capability_runtime_windows enable row level security;
alter table private.capability_runtime_windows force row level security;
revoke all on private.capability_runtime_windows from public, anon, authenticated, service_role;
alter table private.capability_attention_state owner to postgres;
alter table private.capability_attention_state enable row level security;
alter table private.capability_attention_state force row level security;
revoke all on private.capability_attention_state from public, anon, authenticated, service_role;
alter table private.capability_attention_outbox owner to postgres;
alter table private.capability_attention_outbox enable row level security;
alter table private.capability_attention_outbox force row level security;
revoke all on private.capability_attention_outbox from public, anon, authenticated, service_role;
alter table private.capability_attention_evaluations owner to postgres;
alter table private.capability_attention_evaluations enable row level security;
alter table private.capability_attention_evaluations force row level security;
revoke all on private.capability_attention_evaluations from public, anon, authenticated, service_role;
alter function private.capability_runtime_scope(text,text,text,text) owner to postgres;
revoke all on function private.capability_runtime_scope(text,text,text,text) from public,anon,authenticated,service_role;
alter function private.capability_runtime_keys(jsonb,text[]) owner to postgres;
revoke all on function private.capability_runtime_keys(jsonb,text[]) from public,anon,authenticated,service_role;
alter function private.capability_runtime_claim(jsonb) owner to postgres;
revoke all on function private.capability_runtime_claim(jsonb) from public,anon,authenticated,service_role;
alter function private.capability_runtime_complete(jsonb) owner to postgres;
revoke all on function private.capability_runtime_complete(jsonb) from public,anon,authenticated,service_role;
alter function private.capability_runtime_attention(jsonb) owner to postgres;
revoke all on function private.capability_runtime_attention(jsonb) from public,anon,authenticated,service_role;
alter function public.api_claim_capability_window(jsonb) owner to postgres;
revoke all on function public.api_claim_capability_window(jsonb) from public,anon,authenticated,service_role;
grant execute on function public.api_claim_capability_window(jsonb) to service_role;
alter function public.api_complete_capability_window(jsonb) owner to postgres;
revoke all on function public.api_complete_capability_window(jsonb) from public,anon,authenticated,service_role;
grant execute on function public.api_complete_capability_window(jsonb) to service_role;
alter function public.api_commit_capability_attention(jsonb) owner to postgres;
revoke all on function public.api_commit_capability_attention(jsonb) from public,anon,authenticated,service_role;
grant execute on function public.api_commit_capability_attention(jsonb) to service_role;
alter function public.api_get_capability_window(text,uuid) owner to postgres;
revoke all on function public.api_get_capability_window(text,uuid) from public,anon,authenticated,service_role;
grant execute on function public.api_get_capability_window(text,uuid) to service_role;
alter function public.api_read_capability_attention(text) owner to postgres;
revoke all on function public.api_read_capability_attention(text) from public,anon,authenticated,service_role;
grant execute on function public.api_read_capability_attention(text) to service_role;
alter function public.api_list_due_capability_attention(integer) owner to postgres;
revoke all on function public.api_list_due_capability_attention(integer) from public,anon,authenticated,service_role;
grant execute on function public.api_list_due_capability_attention(integer) to service_role;
commit;
