// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type TablesWithRelationships<T extends Record<string, { Row: unknown; Insert: unknown; Update: unknown }>> = {
  [K in keyof T]: T[K] & { Relationships: [] };
};

type ClientDatabase = Omit<Database, 'public'> & {
  public: Omit<Database['public'], 'Tables'> & {
    Tables: TablesWithRelationships<Database['public']['Tables']>;
  };
};

const TEST_SUPABASE_URL = 'https://example.supabase.co';
const TEST_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4YW1wbGUiLCJyb2xlIjoiYW5vbiIsImlhdCI6MCwiZXhwIjo0MTAyNDQ0ODAwfQ.test-signature';

function resolveSupabaseCredentials() {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const publishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (url && publishableKey) {
    return { url, publishableKey };
  }

  if (import.meta.env.MODE === 'test') {
    return {
      url: url ?? TEST_SUPABASE_URL,
      publishableKey: publishableKey ?? TEST_SUPABASE_PUBLISHABLE_KEY,
    };
  }

  throw new Error('VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are required.');
}

const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = resolveSupabaseCredentials();

const noopStorage = {
  getItem: (_key: string) => null,
  setItem: (_key: string, _value: string) => {},
  removeItem: (_key: string) => {},
};

const safeStorage =
  typeof window !== 'undefined' &&
  typeof window.localStorage?.getItem === 'function' &&
  typeof window.localStorage?.setItem === 'function' &&
  typeof window.localStorage?.removeItem === 'function'
    ? window.localStorage
    : noopStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ClientDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: safeStorage !== noopStorage,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
