// Generated by `npm run db:types` against local Supabase migration head.
// Do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      approved_part_requirements: {
        Row: {
          applicable_vendors: Database["public"]["Enums"]["vendor_name"][]
          approved_at: string
          approved_by: string
          created_at: string
          description: string | null
          finish: string | null
          id: string
          material: string
          organization_id: string
          part_id: string
          part_number: string | null
          quantity: number
          quote_quantities: number[]
          requested_by_date: string | null
          revision: string | null
          spec_snapshot: Json
          tightest_tolerance_inch: number | null
          updated_at: string
        }
        Insert: {
          applicable_vendors?: Database["public"]["Enums"]["vendor_name"][]
          approved_at?: string
          approved_by: string
          created_at?: string
          description?: string | null
          finish?: string | null
          id?: string
          material: string
          organization_id: string
          part_id: string
          part_number?: string | null
          quantity?: number
          quote_quantities?: number[]
          requested_by_date?: string | null
          revision?: string | null
          spec_snapshot?: Json
          tightest_tolerance_inch?: number | null
          updated_at?: string
        }
        Update: {
          applicable_vendors?: Database["public"]["Enums"]["vendor_name"][]
          approved_at?: string
          approved_by?: string
          created_at?: string
          description?: string | null
          finish?: string | null
          id?: string
          material?: string
          organization_id?: string
          part_id?: string
          part_number?: string | null
          quantity?: number
          quote_quantities?: number[]
          requested_by_date?: string | null
          revision?: string | null
          spec_snapshot?: Json
          tightest_tolerance_inch?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "approved_part_requirements_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "approved_part_requirements_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: true
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_events: {
        Row: {
          actor_user_id: string | null
          created_at: string
          event_type: string
          id: string
          job_id: string | null
          organization_id: string
          package_id: string | null
          payload: Json
        }
        Insert: {
          actor_user_id?: string | null
          created_at?: string
          event_type: string
          id?: string
          job_id?: string | null
          organization_id: string
          package_id?: string | null
          payload?: Json
        }
        Update: {
          actor_user_id?: string | null
          created_at?: string
          event_type?: string
          id?: string
          job_id?: string | null
          organization_id?: string
          package_id?: string | null
          payload?: Json
        }
        Relationships: [
          {
            foreignKeyName: "audit_events_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_events_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_events_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "published_quote_packages"
            referencedColumns: ["id"]
          },
        ]
      }
      client_selections: {
        Row: {
          created_at: string
          id: string
          note: string | null
          option_id: string
          organization_id: string
          package_id: string
          selected_by: string
        }
        Insert: {
          created_at?: string
          id?: string
          note?: string | null
          option_id: string
          organization_id: string
          package_id: string
          selected_by: string
        }
        Update: {
          created_at?: string
          id?: string
          note?: string | null
          option_id?: string
          organization_id?: string
          package_id?: string
          selected_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "client_selections_option_id_fkey"
            columns: ["option_id"]
            isOneToOne: false
            referencedRelation: "published_quote_options"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "client_selections_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "client_selections_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "published_quote_packages"
            referencedColumns: ["id"]
          },
        ]
      }
      debug_extraction_runs: {
        Row: {
          completed_at: string | null
          created_at: string
          effective_model: string | null
          error: string | null
          extractor_version: string | null
          id: string
          job_id: string
          model_fallback_used: boolean | null
          model_prompt_version: string | null
          organization_id: string
          part_id: string
          requested_by: string
          requested_model: string
          result: Json
          started_at: string | null
          status: Database["public"]["Enums"]["queue_task_status"]
          updated_at: string
          worker_build_version: string | null
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          effective_model?: string | null
          error?: string | null
          extractor_version?: string | null
          id?: string
          job_id: string
          model_fallback_used?: boolean | null
          model_prompt_version?: string | null
          organization_id: string
          part_id: string
          requested_by: string
          requested_model: string
          result?: Json
          started_at?: string | null
          status?: Database["public"]["Enums"]["queue_task_status"]
          updated_at?: string
          worker_build_version?: string | null
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          effective_model?: string | null
          error?: string | null
          extractor_version?: string | null
          id?: string
          job_id?: string
          model_fallback_used?: boolean | null
          model_prompt_version?: string | null
          organization_id?: string
          part_id?: string
          requested_by?: string
          requested_model?: string
          result?: Json
          started_at?: string | null
          status?: Database["public"]["Enums"]["queue_task_status"]
          updated_at?: string
          worker_build_version?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "debug_extraction_runs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "debug_extraction_runs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "debug_extraction_runs_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
        ]
      }
      drawing_extractions: {
        Row: {
          confidence: number | null
          created_at: string
          evidence: Json
          extraction: Json
          extractor_version: string
          id: string
          organization_id: string
          part_id: string
          status: Database["public"]["Enums"]["extraction_status"]
          updated_at: string
          warnings: Json
        }
        Insert: {
          confidence?: number | null
          created_at?: string
          evidence?: Json
          extraction?: Json
          extractor_version?: string
          id?: string
          organization_id: string
          part_id: string
          status?: Database["public"]["Enums"]["extraction_status"]
          updated_at?: string
          warnings?: Json
        }
        Update: {
          confidence?: number | null
          created_at?: string
          evidence?: Json
          extraction?: Json
          extractor_version?: string
          id?: string
          organization_id?: string
          part_id?: string
          status?: Database["public"]["Enums"]["extraction_status"]
          updated_at?: string
          warnings?: Json
        }
        Relationships: [
          {
            foreignKeyName: "drawing_extractions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "drawing_extractions_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: true
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
        ]
      }
      drawing_preview_assets: {
        Row: {
          created_at: string
          height: number | null
          id: string
          kind: string
          organization_id: string
          page_number: number
          part_id: string
          storage_bucket: string
          storage_path: string
          width: number | null
        }
        Insert: {
          created_at?: string
          height?: number | null
          id?: string
          kind?: string
          organization_id: string
          page_number?: number
          part_id: string
          storage_bucket?: string
          storage_path: string
          width?: number | null
        }
        Update: {
          created_at?: string
          height?: number | null
          id?: string
          kind?: string
          organization_id?: string
          page_number?: number
          part_id?: string
          storage_bucket?: string
          storage_path?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "drawing_preview_assets_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "drawing_preview_assets_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
        ]
      }
      job_files: {
        Row: {
          blob_id: string | null
          content_sha256: string | null
          created_at: string
          file_kind: Database["public"]["Enums"]["job_file_kind"]
          id: string
          job_id: string
          matched_part_key: string | null
          mime_type: string | null
          normalized_name: string
          organization_id: string
          original_name: string
          size_bytes: number | null
          storage_bucket: string
          storage_path: string
          uploaded_by: string
        }
        Insert: {
          blob_id?: string | null
          content_sha256?: string | null
          created_at?: string
          file_kind: Database["public"]["Enums"]["job_file_kind"]
          id?: string
          job_id: string
          matched_part_key?: string | null
          mime_type?: string | null
          normalized_name: string
          organization_id: string
          original_name: string
          size_bytes?: number | null
          storage_bucket?: string
          storage_path: string
          uploaded_by: string
        }
        Update: {
          blob_id?: string | null
          content_sha256?: string | null
          created_at?: string
          file_kind?: Database["public"]["Enums"]["job_file_kind"]
          id?: string
          job_id?: string
          matched_part_key?: string | null
          mime_type?: string | null
          normalized_name?: string
          organization_id?: string
          original_name?: string
          size_bytes?: number | null
          storage_bucket?: string
          storage_path?: string
          uploaded_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_files_blob_id_fkey"
            columns: ["blob_id"]
            isOneToOne: false
            referencedRelation: "organization_file_blobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_files_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_files_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          active_pricing_policy_id: string | null
          archived_at: string | null
          created_at: string
          created_by: string
          description: string | null
          id: string
          organization_id: string
          primary_service_kind: string | null
          project_id: string | null
          requested_by_date: string | null
          requested_quote_quantities: number[]
          requested_service_kinds: string[]
          selected_vendor_quote_offer_id: string | null
          service_notes: string | null
          source: string
          status: Database["public"]["Enums"]["job_status"]
          tags: string[]
          title: string
          updated_at: string
        }
        Insert: {
          active_pricing_policy_id?: string | null
          archived_at?: string | null
          created_at?: string
          created_by: string
          description?: string | null
          id?: string
          organization_id: string
          primary_service_kind?: string | null
          project_id?: string | null
          requested_by_date?: string | null
          requested_quote_quantities?: number[]
          requested_service_kinds?: string[]
          selected_vendor_quote_offer_id?: string | null
          service_notes?: string | null
          source?: string
          status?: Database["public"]["Enums"]["job_status"]
          tags?: string[]
          title: string
          updated_at?: string
        }
        Update: {
          active_pricing_policy_id?: string | null
          archived_at?: string | null
          created_at?: string
          created_by?: string
          description?: string | null
          id?: string
          organization_id?: string
          primary_service_kind?: string | null
          project_id?: string | null
          requested_by_date?: string | null
          requested_quote_quantities?: number[]
          requested_service_kinds?: string[]
          selected_vendor_quote_offer_id?: string | null
          service_notes?: string | null
          source?: string
          status?: Database["public"]["Enums"]["job_status"]
          tags?: string[]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_active_pricing_policy_id_fkey"
            columns: ["active_pricing_policy_id"]
            isOneToOne: false
            referencedRelation: "pricing_policies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_selected_vendor_quote_offer_id_fkey"
            columns: ["selected_vendor_quote_offer_id"]
            isOneToOne: false
            referencedRelation: "vendor_quote_offers"
            referencedColumns: ["id"]
          },
        ]
      }
      org_vendor_configs: {
        Row: {
          created_at: string
          enabled_for_client_quote_requests: boolean
          organization_id: string
          updated_at: string
          vendor: Database["public"]["Enums"]["vendor_name"]
        }
        Insert: {
          created_at?: string
          enabled_for_client_quote_requests?: boolean
          organization_id: string
          updated_at?: string
          vendor: Database["public"]["Enums"]["vendor_name"]
        }
        Update: {
          created_at?: string
          enabled_for_client_quote_requests?: boolean
          organization_id?: string
          updated_at?: string
          vendor?: Database["public"]["Enums"]["vendor_name"]
        }
        Relationships: [
          {
            foreignKeyName: "org_vendor_configs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_file_blobs: {
        Row: {
          content_sha256: string
          created_at: string
          id: string
          mime_type: string | null
          organization_id: string
          size_bytes: number | null
          storage_bucket: string
          storage_path: string
        }
        Insert: {
          content_sha256: string
          created_at?: string
          id?: string
          mime_type?: string | null
          organization_id: string
          size_bytes?: number | null
          storage_bucket?: string
          storage_path: string
        }
        Update: {
          content_sha256?: string
          created_at?: string
          id?: string
          mime_type?: string | null
          organization_id?: string
          size_bytes?: number | null
          storage_bucket?: string
          storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_file_blobs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_memberships: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_memberships_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          billing_city: string | null
          billing_country: string | null
          billing_state: string | null
          billing_street: string | null
          billing_zip: string | null
          company_name: string | null
          created_at: string
          id: string
          logo_url: string | null
          name: string
          phone: string | null
          shipping_city: string | null
          shipping_country: string | null
          shipping_same_as_billing: boolean
          shipping_state: string | null
          shipping_street: string | null
          shipping_zip: string | null
          slug: string
          updated_at: string
        }
        Insert: {
          billing_city?: string | null
          billing_country?: string | null
          billing_state?: string | null
          billing_street?: string | null
          billing_zip?: string | null
          company_name?: string | null
          created_at?: string
          id?: string
          logo_url?: string | null
          name: string
          phone?: string | null
          shipping_city?: string | null
          shipping_country?: string | null
          shipping_same_as_billing?: boolean
          shipping_state?: string | null
          shipping_street?: string | null
          shipping_zip?: string | null
          slug: string
          updated_at?: string
        }
        Update: {
          billing_city?: string | null
          billing_country?: string | null
          billing_state?: string | null
          billing_street?: string | null
          billing_zip?: string | null
          company_name?: string | null
          created_at?: string
          id?: string
          logo_url?: string | null
          name?: string
          phone?: string | null
          shipping_city?: string | null
          shipping_country?: string | null
          shipping_same_as_billing?: boolean
          shipping_state?: string | null
          shipping_street?: string | null
          shipping_zip?: string | null
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      parts: {
        Row: {
          cad_file_id: string | null
          created_at: string
          drawing_file_id: string | null
          id: string
          job_id: string
          name: string
          normalized_key: string
          organization_id: string
          quantity: number
          updated_at: string
        }
        Insert: {
          cad_file_id?: string | null
          created_at?: string
          drawing_file_id?: string | null
          id?: string
          job_id: string
          name: string
          normalized_key: string
          organization_id: string
          quantity?: number
          updated_at?: string
        }
        Update: {
          cad_file_id?: string | null
          created_at?: string
          drawing_file_id?: string | null
          id?: string
          job_id?: string
          name?: string
          normalized_key?: string
          organization_id?: string
          quantity?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "parts_cad_file_id_fkey"
            columns: ["cad_file_id"]
            isOneToOne: false
            referencedRelation: "job_files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parts_drawing_file_id_fkey"
            columns: ["drawing_file_id"]
            isOneToOne: false
            referencedRelation: "job_files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      pricing_policies: {
        Row: {
          created_at: string
          currency_minor_unit: number
          id: string
          is_active: boolean
          markup_percent: number
          notes: string | null
          organization_id: string | null
          version: string
        }
        Insert: {
          created_at?: string
          currency_minor_unit?: number
          id?: string
          is_active?: boolean
          markup_percent?: number
          notes?: string | null
          organization_id?: string | null
          version: string
        }
        Update: {
          created_at?: string
          currency_minor_unit?: number
          id?: string
          is_active?: boolean
          markup_percent?: number
          notes?: string | null
          organization_id?: string | null
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "pricing_policies_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      project_invites: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string
          project_id: string
          revoked_at: string | null
          role: Database["public"]["Enums"]["project_role"]
          status: Database["public"]["Enums"]["project_invite_status"]
          token: string
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by: string
          project_id: string
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["project_role"]
          status?: Database["public"]["Enums"]["project_invite_status"]
          token: string
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string
          project_id?: string
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["project_role"]
          status?: Database["public"]["Enums"]["project_invite_status"]
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_invites_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_jobs: {
        Row: {
          created_at: string
          created_by: string
          id: string
          job_id: string
          project_id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          id?: string
          job_id: string
          project_id: string
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          job_id?: string
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_jobs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_jobs_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_memberships: {
        Row: {
          created_at: string
          id: string
          project_id: string
          role: Database["public"]["Enums"]["project_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          project_id: string
          role?: Database["public"]["Enums"]["project_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          project_id?: string
          role?: Database["public"]["Enums"]["project_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_memberships_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          archived_at: string | null
          created_at: string
          description: string | null
          id: string
          name: string
          organization_id: string
          owner_user_id: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name: string
          organization_id: string
          owner_user_id: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          organization_id?: string
          owner_user_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      published_quote_options: {
        Row: {
          comparison_summary: string | null
          created_at: string
          id: string
          label: string
          lead_time_business_days: number | null
          markup_policy_version: string
          option_kind: Database["public"]["Enums"]["client_option_kind"]
          organization_id: string
          package_id: string
          published_price_usd: number
          requested_quantity: number
          source_vendor_quote_id: string
          source_vendor_quote_offer_id: string | null
        }
        Insert: {
          comparison_summary?: string | null
          created_at?: string
          id?: string
          label: string
          lead_time_business_days?: number | null
          markup_policy_version: string
          option_kind: Database["public"]["Enums"]["client_option_kind"]
          organization_id: string
          package_id: string
          published_price_usd: number
          requested_quantity?: number
          source_vendor_quote_id: string
          source_vendor_quote_offer_id?: string | null
        }
        Update: {
          comparison_summary?: string | null
          created_at?: string
          id?: string
          label?: string
          lead_time_business_days?: number | null
          markup_policy_version?: string
          option_kind?: Database["public"]["Enums"]["client_option_kind"]
          organization_id?: string
          package_id?: string
          published_price_usd?: number
          requested_quantity?: number
          source_vendor_quote_id?: string
          source_vendor_quote_offer_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "published_quote_options_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_quote_options_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "published_quote_packages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_quote_options_source_vendor_quote_id_fkey"
            columns: ["source_vendor_quote_id"]
            isOneToOne: false
            referencedRelation: "vendor_quote_results"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_quote_options_source_vendor_quote_offer_id_fkey"
            columns: ["source_vendor_quote_offer_id"]
            isOneToOne: false
            referencedRelation: "vendor_quote_offers"
            referencedColumns: ["id"]
          },
        ]
      }
      published_quote_packages: {
        Row: {
          auto_published: boolean
          client_summary: string | null
          created_at: string
          id: string
          job_id: string
          organization_id: string
          pricing_policy_id: string
          published_at: string
          published_by: string
          quote_run_id: string
        }
        Insert: {
          auto_published?: boolean
          client_summary?: string | null
          created_at?: string
          id?: string
          job_id: string
          organization_id: string
          pricing_policy_id: string
          published_at?: string
          published_by: string
          quote_run_id: string
        }
        Update: {
          auto_published?: boolean
          client_summary?: string | null
          created_at?: string
          id?: string
          job_id?: string
          organization_id?: string
          pricing_policy_id?: string
          published_at?: string
          published_by?: string
          quote_run_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "published_quote_packages_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_quote_packages_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_quote_packages_pricing_policy_id_fkey"
            columns: ["pricing_policy_id"]
            isOneToOne: false
            referencedRelation: "pricing_policies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "published_quote_packages_quote_run_id_fkey"
            columns: ["quote_run_id"]
            isOneToOne: true
            referencedRelation: "quote_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      quote_request_guardrails: {
        Row: {
          created_at: string
          default_cost_per_requested_lane_usd: number
          enabled: boolean
          org_pending_cost_ceiling_usd: number
          organization_id: string
          updated_at: string
          user_max_requests_per_window: number
          user_window_minutes: number
        }
        Insert: {
          created_at?: string
          default_cost_per_requested_lane_usd?: number
          enabled?: boolean
          org_pending_cost_ceiling_usd?: number
          organization_id: string
          updated_at?: string
          user_max_requests_per_window?: number
          user_window_minutes?: number
        }
        Update: {
          created_at?: string
          default_cost_per_requested_lane_usd?: number
          enabled?: boolean
          org_pending_cost_ceiling_usd?: number
          organization_id?: string
          updated_at?: string
          user_max_requests_per_window?: number
          user_window_minutes?: number
        }
        Relationships: [
          {
            foreignKeyName: "quote_request_guardrails_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      quote_requests: {
        Row: {
          canceled_at: string | null
          created_at: string
          failed_at: string | null
          failure_reason: string | null
          id: string
          job_id: string
          organization_id: string
          received_at: string | null
          requested_by: string
          requested_vendors: Database["public"]["Enums"]["vendor_name"][]
          service_request_line_item_id: string | null
          status: Database["public"]["Enums"]["quote_request_status"]
          updated_at: string
        }
        Insert: {
          canceled_at?: string | null
          created_at?: string
          failed_at?: string | null
          failure_reason?: string | null
          id?: string
          job_id: string
          organization_id: string
          received_at?: string | null
          requested_by: string
          requested_vendors?: Database["public"]["Enums"]["vendor_name"][]
          service_request_line_item_id?: string | null
          status?: Database["public"]["Enums"]["quote_request_status"]
          updated_at?: string
        }
        Update: {
          canceled_at?: string | null
          created_at?: string
          failed_at?: string | null
          failure_reason?: string | null
          id?: string
          job_id?: string
          organization_id?: string
          received_at?: string | null
          requested_by?: string
          requested_vendors?: Database["public"]["Enums"]["vendor_name"][]
          service_request_line_item_id?: string | null
          status?: Database["public"]["Enums"]["quote_request_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quote_requests_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_requests_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_requests_service_request_line_item_id_fkey"
            columns: ["service_request_line_item_id"]
            isOneToOne: false
            referencedRelation: "service_request_line_items"
            referencedColumns: ["id"]
          },
        ]
      }
      quote_runs: {
        Row: {
          created_at: string
          id: string
          initiated_by: string
          job_id: string
          organization_id: string
          quote_request_id: string | null
          requested_auto_publish: boolean
          status: Database["public"]["Enums"]["quote_run_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          initiated_by: string
          job_id: string
          organization_id: string
          quote_request_id?: string | null
          requested_auto_publish?: boolean
          status?: Database["public"]["Enums"]["quote_run_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          initiated_by?: string
          job_id?: string
          organization_id?: string
          quote_request_id?: string | null
          requested_auto_publish?: boolean
          status?: Database["public"]["Enums"]["quote_run_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quote_runs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_runs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_runs_quote_request_id_fkey"
            columns: ["quote_request_id"]
            isOneToOne: false
            referencedRelation: "quote_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      service_request_line_items: {
        Row: {
          created_at: string
          id: string
          job_id: string | null
          organization_id: string
          project_id: string | null
          scope: string
          service_detail: Json
          service_type: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          job_id?: string | null
          organization_id: string
          project_id?: string | null
          scope?: string
          service_detail?: Json
          service_type: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          job_id?: string | null
          organization_id?: string
          project_id?: string | null
          scope?: string
          service_detail?: Json
          service_type?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_request_line_items_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_request_line_items_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_request_line_items_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      user_pinned_jobs: {
        Row: {
          created_at: string
          id: string
          job_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          job_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          job_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_pinned_jobs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      user_pinned_projects: {
        Row: {
          created_at: string
          id: string
          project_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          project_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          project_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_pinned_projects_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_quote_artifacts: {
        Row: {
          artifact_type: string
          created_at: string
          id: string
          metadata: Json
          organization_id: string
          storage_bucket: string
          storage_path: string
          vendor_quote_result_id: string
        }
        Insert: {
          artifact_type: string
          created_at?: string
          id?: string
          metadata?: Json
          organization_id: string
          storage_bucket?: string
          storage_path: string
          vendor_quote_result_id: string
        }
        Update: {
          artifact_type?: string
          created_at?: string
          id?: string
          metadata?: Json
          organization_id?: string
          storage_bucket?: string
          storage_path?: string
          vendor_quote_result_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_quote_artifacts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_quote_artifacts_vendor_quote_result_id_fkey"
            columns: ["vendor_quote_result_id"]
            isOneToOne: false
            referencedRelation: "vendor_quote_results"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_quote_offers: {
        Row: {
          created_at: string
          due_date: string | null
          finish: string | null
          id: string
          lane_label: string
          lead_time_business_days: number | null
          material: string | null
          notes: string | null
          offer_key: string
          organization_id: string
          process: string | null
          quote_date: string | null
          quote_ref: string | null
          raw_payload: Json
          ship_receive_by: string | null
          sort_rank: number
          sourcing: string | null
          supplier: string
          thread_callouts: string | null
          thread_match_notes: string | null
          tier: string | null
          tightest_tolerance: string | null
          tolerance_source: string | null
          total_price_usd: number | null
          unit_price_usd: number | null
          updated_at: string
          vendor_quote_result_id: string
        }
        Insert: {
          created_at?: string
          due_date?: string | null
          finish?: string | null
          id?: string
          lane_label: string
          lead_time_business_days?: number | null
          material?: string | null
          notes?: string | null
          offer_key: string
          organization_id: string
          process?: string | null
          quote_date?: string | null
          quote_ref?: string | null
          raw_payload?: Json
          ship_receive_by?: string | null
          sort_rank?: number
          sourcing?: string | null
          supplier: string
          thread_callouts?: string | null
          thread_match_notes?: string | null
          tier?: string | null
          tightest_tolerance?: string | null
          tolerance_source?: string | null
          total_price_usd?: number | null
          unit_price_usd?: number | null
          updated_at?: string
          vendor_quote_result_id: string
        }
        Update: {
          created_at?: string
          due_date?: string | null
          finish?: string | null
          id?: string
          lane_label?: string
          lead_time_business_days?: number | null
          material?: string | null
          notes?: string | null
          offer_key?: string
          organization_id?: string
          process?: string | null
          quote_date?: string | null
          quote_ref?: string | null
          raw_payload?: Json
          ship_receive_by?: string | null
          sort_rank?: number
          sourcing?: string | null
          supplier?: string
          thread_callouts?: string | null
          thread_match_notes?: string | null
          tier?: string | null
          tightest_tolerance?: string | null
          tolerance_source?: string | null
          total_price_usd?: number | null
          unit_price_usd?: number | null
          updated_at?: string
          vendor_quote_result_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_quote_offers_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_quote_offers_vendor_quote_result_id_fkey"
            columns: ["vendor_quote_result_id"]
            isOneToOne: false
            referencedRelation: "vendor_quote_results"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_quote_results: {
        Row: {
          created_at: string
          dfm_issues: Json
          id: string
          lead_time_business_days: number | null
          notes: Json
          organization_id: string
          part_id: string
          quote_run_id: string
          quote_url: string | null
          raw_payload: Json
          requested_quantity: number
          status: Database["public"]["Enums"]["vendor_status"]
          total_price_usd: number | null
          unit_price_usd: number | null
          updated_at: string
          vendor: Database["public"]["Enums"]["vendor_name"]
        }
        Insert: {
          created_at?: string
          dfm_issues?: Json
          id?: string
          lead_time_business_days?: number | null
          notes?: Json
          organization_id: string
          part_id: string
          quote_run_id: string
          quote_url?: string | null
          raw_payload?: Json
          requested_quantity?: number
          status?: Database["public"]["Enums"]["vendor_status"]
          total_price_usd?: number | null
          unit_price_usd?: number | null
          updated_at?: string
          vendor: Database["public"]["Enums"]["vendor_name"]
        }
        Update: {
          created_at?: string
          dfm_issues?: Json
          id?: string
          lead_time_business_days?: number | null
          notes?: Json
          organization_id?: string
          part_id?: string
          quote_run_id?: string
          quote_url?: string | null
          raw_payload?: Json
          requested_quantity?: number
          status?: Database["public"]["Enums"]["vendor_status"]
          total_price_usd?: number | null
          unit_price_usd?: number | null
          updated_at?: string
          vendor?: Database["public"]["Enums"]["vendor_name"]
        }
        Relationships: [
          {
            foreignKeyName: "vendor_quote_results_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_quote_results_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_quote_results_quote_run_id_fkey"
            columns: ["quote_run_id"]
            isOneToOne: false
            referencedRelation: "quote_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      work_queue: {
        Row: {
          attempts: number
          available_at: string
          created_at: string
          id: string
          job_id: string | null
          last_error: string | null
          locked_at: string | null
          locked_by: string | null
          organization_id: string
          package_id: string | null
          part_id: string | null
          payload: Json
          quote_run_id: string | null
          status: Database["public"]["Enums"]["queue_task_status"]
          task_type: Database["public"]["Enums"]["queue_task_type"]
          updated_at: string
        }
        Insert: {
          attempts?: number
          available_at?: string
          created_at?: string
          id?: string
          job_id?: string | null
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          organization_id: string
          package_id?: string | null
          part_id?: string | null
          payload?: Json
          quote_run_id?: string | null
          status?: Database["public"]["Enums"]["queue_task_status"]
          task_type: Database["public"]["Enums"]["queue_task_type"]
          updated_at?: string
        }
        Update: {
          attempts?: number
          available_at?: string
          created_at?: string
          id?: string
          job_id?: string | null
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          organization_id?: string
          package_id?: string | null
          part_id?: string | null
          payload?: Json
          quote_run_id?: string | null
          status?: Database["public"]["Enums"]["queue_task_status"]
          task_type?: Database["public"]["Enums"]["queue_task_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_queue_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_queue_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_queue_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "published_quote_packages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_queue_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_queue_quote_run_id_fkey"
            columns: ["quote_run_id"]
            isOneToOne: false
            referencedRelation: "quote_runs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      extraction_quality_summary: {
        Row: {
          auto_approve_rate: number | null
          auto_approved_extractions: number | null
          completed_extractions: number | null
          day: string | null
          model_fallback_extractions: number | null
          model_fallback_rate: number | null
          needs_review_extractions: number | null
          organization_id: string | null
          partial_lifecycle_extractions: number | null
          warning_extractions: number | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_events_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      api_accept_project_invite: { Args: { p_token: string }; Returns: string }
      api_admin_list_all_jobs: { Args: never; Returns: Json }
      api_admin_list_all_projects: { Args: never; Returns: Json }
      api_admin_list_all_users: { Args: never; Returns: Json }
      api_admin_list_organizations: { Args: never; Returns: Json }
      api_approve_job_requirements: {
        Args: { p_job_id: string; p_requirements: Json }
        Returns: number
      }
      api_archive_job: { Args: { p_job_id: string }; Returns: string }
      api_archive_project: { Args: { p_project_id: string }; Returns: string }
      api_assign_job_to_project: {
        Args: { p_job_id: string; p_project_id: string }
        Returns: string
      }
      api_attach_job_file: {
        Args: {
          p_file_kind: Database["public"]["Enums"]["job_file_kind"]
          p_job_id: string
          p_mime_type?: string
          p_original_name: string
          p_size_bytes?: number
          p_storage_bucket: string
          p_storage_path: string
        }
        Returns: string
      }
      api_auto_approve_job_requirements: {
        Args: { p_job_id: string }
        Returns: number
      }
      api_cancel_quote_request: {
        Args: { p_request_id: string }
        Returns: Json
      }
      api_claim_next_task: {
        Args: { p_worker_name: string }
        Returns: {
          attempts: number
          available_at: string
          created_at: string
          id: string
          job_id: string | null
          last_error: string | null
          locked_at: string | null
          locked_by: string | null
          organization_id: string
          package_id: string | null
          part_id: string | null
          payload: Json
          quote_run_id: string | null
          status: Database["public"]["Enums"]["queue_task_status"]
          task_type: Database["public"]["Enums"]["queue_task_type"]
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "work_queue"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      api_create_client_draft: {
        Args: {
          p_description?: string
          p_primary_service_kind?: string
          p_project_id?: string
          p_requested_by_date?: string
          p_requested_quote_quantities?: number[]
          p_requested_service_kinds?: string[]
          p_service_notes?: string
          p_tags?: string[]
          p_title: string
        }
        Returns: string
      }
      api_create_job: {
        Args: {
          p_description?: string
          p_organization_id: string
          p_primary_service_kind?: string
          p_requested_by_date?: string
          p_requested_quote_quantities?: number[]
          p_requested_service_kinds?: string[]
          p_service_notes?: string
          p_source?: string
          p_tags?: string[]
          p_title: string
        }
        Returns: string
      }
      api_create_project: {
        Args: { p_description?: string; p_name: string }
        Returns: string
      }
      api_create_self_service_organization: {
        Args: { p_organization_name: string }
        Returns: string
      }
      api_delete_archived_job: { Args: { p_job_id: string }; Returns: string }
      api_delete_archived_jobs: { Args: { p_job_ids: string[] }; Returns: Json }
      api_delete_project: { Args: { p_project_id: string }; Returns: string }
      api_dissolve_project: { Args: { p_project_id: string }; Returns: string }
      api_enqueue_debug_vendor_quote: {
        Args: {
          p_part_id: string
          p_quote_run_id: string
          p_requested_quantity: number
          p_vendor: Database["public"]["Enums"]["vendor_name"]
        }
        Returns: Json
      }
      api_finalize_job_file_upload: {
        Args: {
          p_content_sha256?: string
          p_file_kind: Database["public"]["Enums"]["job_file_kind"]
          p_job_id: string
          p_mime_type?: string
          p_original_name: string
          p_size_bytes?: number
          p_storage_bucket: string
          p_storage_path: string
        }
        Returns: string
      }
      api_get_client_intake_compatibility: { Args: never; Returns: Json }
      api_get_is_platform_admin: { Args: never; Returns: boolean }
      api_get_quote_run_readiness: {
        Args: { p_quote_run_id: string }
        Returns: Json
      }
      api_invite_project_member: {
        Args: {
          p_email: string
          p_project_id: string
          p_role?: Database["public"]["Enums"]["project_role"]
        }
        Returns: Json
      }
      api_list_client_activity_events: {
        Args: { p_job_ids: string[]; p_limit_per_job?: number }
        Returns: Json
      }
      api_list_client_part_metadata: {
        Args: { p_job_ids: string[] }
        Returns: Json
      }
      api_list_client_quote_workspace: {
        Args: { p_job_ids: string[] }
        Returns: Json
      }
      api_list_organization_memberships: {
        Args: { p_organization_id: string }
        Returns: Json
      }
      api_list_project_assignee_profiles: {
        Args: { p_project_id: string }
        Returns: Json
      }
      api_prepare_job_file_upload: {
        Args: {
          p_content_sha256?: string
          p_file_kind: Database["public"]["Enums"]["job_file_kind"]
          p_job_id: string
          p_mime_type?: string
          p_original_name: string
          p_size_bytes?: number
        }
        Returns: Json
      }
      api_publish_quote_package: {
        Args: {
          p_client_summary?: string
          p_force?: boolean
          p_job_id: string
          p_quote_run_id: string
        }
        Returns: string
      }
      api_reconcile_job_parts: { Args: { p_job_id: string }; Returns: Json }
      api_record_manual_vendor_quote: {
        Args: {
          p_artifacts?: Json
          p_job_id: string
          p_offers?: Json
          p_part_id: string
          p_quote_url?: string
          p_source_text?: string
          p_status?: Database["public"]["Enums"]["vendor_status"]
          p_summary_note?: string
          p_vendor: Database["public"]["Enums"]["vendor_name"]
        }
        Returns: Json
      }
      api_remove_job_from_project: {
        Args: { p_job_id: string; p_project_id: string }
        Returns: string
      }
      api_remove_project_member: {
        Args: { p_project_membership_id: string }
        Returns: string
      }
      api_request_debug_extraction: {
        Args: { p_model?: string; p_part_id: string }
        Returns: string
      }
      api_request_extraction: { Args: { p_job_id: string }; Returns: number }
      api_request_quote: {
        Args: { p_force_retry?: boolean; p_job_id: string }
        Returns: Json
      }
      api_request_quotes: {
        Args: { p_force_retry?: boolean; p_job_ids: string[] }
        Returns: Json
      }
      api_select_quote_option: {
        Args: { p_note?: string; p_option_id: string; p_package_id: string }
        Returns: string
      }
      api_set_job_selected_vendor_quote_offer: {
        Args: { p_job_id: string; p_vendor_quote_offer_id?: string }
        Returns: string
      }
      api_start_quote_run: {
        Args: { p_auto_publish_requested?: boolean; p_job_id: string }
        Returns: string
      }
      api_unarchive_job: { Args: { p_job_id: string }; Returns: string }
      api_unarchive_project: { Args: { p_project_id: string }; Returns: string }
      api_update_client_part_request: {
        Args: {
          p_certifications?: Json
          p_description?: string
          p_finish?: string
          p_job_id: string
          p_material?: string
          p_notes?: string
          p_part_number?: string
          p_primary_service_kind?: string
          p_process?: string
          p_quantity?: number
          p_release?: Json
          p_requested_by_date?: string
          p_requested_quote_quantities?: number[]
          p_requested_service_kinds?: string[]
          p_revision?: string
          p_service_notes?: string
          p_shipping?: Json
          p_sourcing?: Json
          p_tightest_tolerance_inch?: number
        }
        Returns: string
      }
      api_update_organization_membership_role: {
        Args: {
          p_membership_id: string
          p_role: Database["public"]["Enums"]["app_role"]
        }
        Returns: string
      }
      api_update_project: {
        Args: { p_description?: string; p_name: string; p_project_id: string }
        Returns: string
      }
      apply_markup: {
        Args: {
          p_markup_percent: number
          p_minor_unit: number
          p_raw_amount: number
        }
        Returns: number
      }
      build_manufacturing_quote_service_detail: {
        Args: { p_job_id: string }
        Returns: Json
      }
      build_org_file_blob_storage_path: {
        Args: {
          p_content_sha256: string
          p_organization_id: string
          p_original_name: string
        }
        Returns: string
      }
      current_user_has_verified_auth: { Args: never; Returns: boolean }
      current_user_home_organization_id: { Args: never; Returns: string }
      get_active_pricing_policy_id: {
        Args: { p_organization_id: string }
        Returns: string
      }
      get_enabled_client_quote_vendors: {
        Args: { p_organization_id: string }
        Returns: Database["public"]["Enums"]["vendor_name"][]
      }
      get_quote_request_guardrails: {
        Args: { p_organization_id: string }
        Returns: Json
      }
      get_quote_request_pending_estimated_cost_usd: {
        Args: { p_organization_id: string }
        Returns: number
      }
      get_self_service_membership_role: {
        Args: { p_user_id: string }
        Returns: Database["public"]["Enums"]["app_role"]
      }
      insert_published_quote_option: {
        Args: {
          p_markup_percent: number
          p_markup_version: string
          p_minor_unit: number
          p_option_kind: Database["public"]["Enums"]["client_option_kind"]
          p_package_id: string
          p_requested_quantity: number
          p_vendor_quote_id: string
          p_vendor_quote_offer_id?: string
        }
        Returns: string
      }
      is_internal_user: {
        Args: { p_organization_id: string }
        Returns: boolean
      }
      is_org_admin: { Args: { p_organization_id: string }; Returns: boolean }
      is_platform_admin: { Args: never; Returns: boolean }
      job_part_file_set: {
        Args: { p_job_id: string }
        Returns: {
          cad_file_id: string
          drawing_file_id: string
          normalized_name: string
        }[]
      }
      log_audit_event: {
        Args: {
          p_event_type: string
          p_job_id?: string
          p_organization_id: string
          p_package_id?: string
          p_payload?: Json
        }
        Returns: string
      }
      normalize_file_basename: { Args: { input_name: string }; Returns: string }
      normalize_positive_integer_array: {
        Args: { p_fallback?: number; p_values: number[] }
        Returns: number[]
      }
      normalize_primary_service_kind: {
        Args: {
          p_primary_service_kind?: string
          p_requested_service_kinds?: string[]
        }
        Returns: string
      }
      normalize_requested_service_kinds: {
        Args: {
          p_primary_service_kind?: string
          p_requested_service_kinds?: string[]
        }
        Returns: string[]
      }
      require_verified_auth: { Args: never; Returns: undefined }
      sync_quote_request_status_for_run: {
        Args: { p_failure_reason?: string; p_quote_run_id: string }
        Returns: Database["public"]["Enums"]["quote_request_status"]
      }
      to_vendor_name_array: {
        Args: { payload: Json }
        Returns: Database["public"]["Enums"]["vendor_name"][]
      }
      user_can_access_job: { Args: { p_job_id: string }; Returns: boolean }
      user_can_access_job_via_project: {
        Args: { p_job_id: string }
        Returns: boolean
      }
      user_can_access_org: {
        Args: { p_organization_id: string }
        Returns: boolean
      }
      user_can_access_package: {
        Args: { p_package_id: string }
        Returns: boolean
      }
      user_can_access_project: {
        Args: { p_project_id: string }
        Returns: boolean
      }
      user_can_edit_job: { Args: { p_job_id: string }; Returns: boolean }
      user_can_edit_project: {
        Args: { p_project_id: string }
        Returns: boolean
      }
      user_is_project_owner: {
        Args: { p_project_id: string }
        Returns: boolean
      }
    }
    Enums: {
      app_role: "client" | "internal_estimator" | "internal_admin"
      client_option_kind: "lowest_cost" | "fastest_delivery" | "balanced"
      extraction_status: "needs_review" | "approved"
      job_file_kind: "cad" | "drawing" | "artifact" | "other"
      job_status:
        | "uploaded"
        | "extracting"
        | "needs_spec_review"
        | "ready_to_quote"
        | "quoting"
        | "awaiting_vendor_manual_review"
        | "internal_review"
        | "published"
        | "client_selected"
        | "closed"
      project_invite_status: "pending" | "accepted" | "revoked" | "expired"
      project_role: "owner" | "editor"
      queue_task_status:
        | "queued"
        | "running"
        | "completed"
        | "failed"
        | "cancelled"
      queue_task_type:
        | "extract_part"
        | "run_vendor_quote"
        | "poll_vendor_quote"
        | "publish_package"
        | "repair_adapter_candidate"
        | "debug_extract_part"
      quote_request_status:
        | "queued"
        | "requesting"
        | "received"
        | "failed"
        | "canceled"
      quote_run_status:
        | "queued"
        | "running"
        | "completed"
        | "failed"
        | "published"
      vendor_name:
        | "xometry"
        | "fictiv"
        | "protolabs"
        | "sendcutsend"
        | "partsbadger"
        | "fastdms"
        | "devzmanufacturing"
        | "infraredlaboratories"
      vendor_status:
        | "queued"
        | "running"
        | "instant_quote_received"
        | "official_quote_received"
        | "manual_review_pending"
        | "manual_vendor_followup"
        | "failed"
        | "stale"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      app_role: ["client", "internal_estimator", "internal_admin"],
      client_option_kind: ["lowest_cost", "fastest_delivery", "balanced"],
      extraction_status: ["needs_review", "approved"],
      job_file_kind: ["cad", "drawing", "artifact", "other"],
      job_status: [
        "uploaded",
        "extracting",
        "needs_spec_review",
        "ready_to_quote",
        "quoting",
        "awaiting_vendor_manual_review",
        "internal_review",
        "published",
        "client_selected",
        "closed",
      ],
      project_invite_status: ["pending", "accepted", "revoked", "expired"],
      project_role: ["owner", "editor"],
      queue_task_status: [
        "queued",
        "running",
        "completed",
        "failed",
        "cancelled",
      ],
      queue_task_type: [
        "extract_part",
        "run_vendor_quote",
        "poll_vendor_quote",
        "publish_package",
        "repair_adapter_candidate",
        "debug_extract_part",
      ],
      quote_request_status: [
        "queued",
        "requesting",
        "received",
        "failed",
        "canceled",
      ],
      quote_run_status: [
        "queued",
        "running",
        "completed",
        "failed",
        "published",
      ],
      vendor_name: [
        "xometry",
        "fictiv",
        "protolabs",
        "sendcutsend",
        "partsbadger",
        "fastdms",
        "devzmanufacturing",
        "infraredlaboratories",
      ],
      vendor_status: [
        "queued",
        "running",
        "instant_quote_received",
        "official_quote_received",
        "manual_review_pending",
        "manual_vendor_followup",
        "failed",
        "stale",
      ],
    },
  },
} as const

// Compatibility aliases preserved for existing app imports.
export type AppRole = Enums<"app_role">
export type ClientOptionKind = Enums<"client_option_kind">
export type ExtractionStatus = Enums<"extraction_status">
export type JobFileKind = Enums<"job_file_kind">
export type JobStatus = Enums<"job_status">
export type ProjectInviteStatus = Enums<"project_invite_status">
export type ProjectRole = Enums<"project_role">
export type QueueTaskStatus = Enums<"queue_task_status">
export type QueueTaskType = Enums<"queue_task_type">
export type QuoteRequestStatus = Enums<"quote_request_status">
export type QuoteRunStatus = Enums<"quote_run_status">
export type VendorName = Enums<"vendor_name">
export type VendorStatus = Enums<"vendor_status">
